.c8rc
package-lock.json
package.json
system-test/github.ts

upgrades to newer version of c8, which works better with TypeScript.

chore: upgrade to newer version of c8

---

package.json
src/bin/release-please.ts
src/github.ts
src/mint-release.ts
system-test/github.ts

could not handle the very first release of a library before it had any tags.

fix: could not handle the very first release of a library before it had any tags.

---

.github/action/candidate-issue/Dockerfile
.github/action/candidate-issue/LICENSE.txt
.github/action/candidate-issue/entrypoint.sh
.github/main.workflow

During testing, this action will fire every five minutes, and attempt to update our candidate release issue.
Once we've tested that this is functional, we will rollback to every 15 minutes.

feat: add GitHub action for generating candidate issue

---

.kokoro/continuous/node10/common.cfg
.kokoro/continuous/node10/test.cfg
.kokoro/presubmit/node10/common.cfg
.kokoro/presubmit/node10/test.cfg

codecov token should be available for continuous and presubmit.

build: move codecov token to common

---

src/bin/release-please.ts

This allows the output to be redirectable to a file immediately.

fix(generate-action): write instructions on stderr

---

__snapshots__/release-pr.js
src/release-pr.ts
src/updaters/php-manifest.ts
test/release-pr.ts

see: https://github.com/googleapis/google-cloud-php/pull/2060

fix: src/manifest.json needs 'v' prefix and top level version

---

.kokoro/continuous/node12/common.cfg
.kokoro/presubmit/node12/common.cfg
synth.metadata
synth.py

Let's make sure this worked properly :smile:

build: configuring Node 12

---

src/graphql-to-commits.ts
src/releasers/java-auth-yoshi.ts
src/releasers/java-yoshi.ts
src/releasers/node.ts
src/releasers/php-yoshi.ts
src/releasers/ruby-yoshi.ts

* if only fixes have landed, docs will show up in fix.
* if features have landed, docs will show up in features.

fix: docs should not count as feature

---

__snapshots__/setup-py.js
src/bin/release-please.ts
src/release-pr-factory.ts
src/release-pr.ts
src/releasers/python.ts
src/updaters/python/setup-py.ts
test/updaters/fixtures/setup.py
test/updaters/setup-py.ts

Follow up to #266. (I don't have write access to this repo :sweat_smile:) This adds a single test for the replacement to the version in `setup.py`.

feat: add initial support for Python libraries

---

src/releasers/node.ts

feat: populate packageName from package.json

---

src/release-pr.ts
test/release-pr.ts

This PR introduces the feature described in #293, we will now look for a Release-As: footer, and this will take precedence over the recommended bump, e.g.,
```
feat: promote to GA
Release-As: 1.0.0
```
@dazuma, @TheRoyalTnetennba, you will likely want to use this in conjunction with adding the option `--bump-minor-pre-major` [here](https://github.com/googleapis/google-cloud-ruby/blob/7eccd8de23974523ef463e5e5d269ffb5bef455b/rakelib/kokoro/kokoro.rb#L149), so that you can get the workflow you've described to me.
closes #293

feat: adds support for release-as footer

---

__snapshots__/java-yoshi.js
src/releasers/java-yoshi.ts
src/updaters/java/google-utils.ts
test/releasers/fixtures/GoogleUtils.java
test/releasers/java-yoshi.ts

this adds support for updating the version in `GoogleUtils.java`.

feat: update GoogleUtils.java

---

src/releasers/python.ts

fix(python): set initial version to 0.1.0

---

__snapshots__/setup-cfg.js
src/releasers/python.ts
src/updaters/python/setup-cfg.ts
test/updaters/fixtures/setup.cfg
test/updaters/setup-cfg.ts

Python supports using a config file for settings as well as in setup.py.

feat(python): Add support to change version in setup.cfg

---

__snapshots__/indent-commit.js
src/util/indent-commit.ts
test/util/indent-commit.ts
tsconfig.json

handles multi-line bulleted commit messages.
fixes: #287

feat: handle multiline bulleted commit messages

---

src/releasers/java-yoshi.ts

there was a bug with the delay logic for snapshots.

fix: make the sleep logic actually work

---

__snapshots__/package-json.js
test/updaters/fixtures/package.json

suppress the security warning that GitHub is giving us through dependabot.

chore: we are getting a false security warning

---

README.md

docs: fix link for python example

---

src/index.ts

Fixes https://github.com/googleapis/release-please/issues/249

feat: add typescript exports from index

---

src/bin/release-please.ts
src/github.ts
src/release-pr.ts

expose `fork` as a config setting.

feat: add option to create PR from fork

---

src/github-release.ts

The release-please-action outputs this URL.

fix: add back upload_url

---

README.md
src/release-pr.ts

A few Python folks have asked how to do this recently.
I had trouble with the wordsmithing, suggestions are very much appreciated.

docs: explain `Release-As`

---

.github/header-checker-lint.yml

Fixes #679 🦕
See [here](https://github.com/googleapis/repo-automation-bots/blob/628e32c2dfa237b536ae4c00366d4ef3acc703f3/.github/header-checker-lint.yml#L1) and [here](https://github.com/googleapis/repo-automation-bots/tree/master/packages/header-checker-lint#configuration) for more information.

chore: disable header check for snapshots

---

CONTRIBUTING.md
package.json
synth.py

Fixes #676 🦕
Related to https://github.com/googleapis/release-please/pull/419

docs: update contributing guide

---

src/releasers/go-yoshi.ts

chore: remove unused constant

---

src/releasers/go-yoshi.ts

chore: cleanup linter warnings

---

__snapshots__/github.js
src/github-release.ts
src/github.ts
test/fixtures/create-comment-response.json
test/github-release.ts
test/github.ts

feat: tagging the release also comments on the release PR

---

src/github.ts

This functionality should be covered by the tests for `commitsSince` and `findMergeCommit` which were refactored to use the async iterator.

feat: add async interator for searching commit history

---

src/release-pr.ts

Also removes extra unused filter criteria (labels). When searching for latestTag, we don't care about the PR labels so remove that filter check.

refactor: squash helper method into ReleasePR.latestTag

---

__snapshots__/helm.js
test/releasers/fixtures/helm/Chart.yaml
test/releasers/helm/helm.ts

Fixes #747 🦕
Helm Test Case. @bcoe Created a test case for helm based on rust as you suggested. Let me know if I missed anything

chore: helm test case

---

__snapshots__/node.js
src/release-pr.ts
src/releasers/node.ts
test/releasers/node.ts

Fixes #558 https://github.com/google-github-actions/release-please-action/issues/168 🦕

fix(release-pr): update default initial version

---

__snapshots__/terraform-module.js
src/updaters/terraform/module-version.ts
test/releasers/fixtures/terraform/simple-module/readme.md
test/releasers/fixtures/terraform/simple-module/versions.tf
test/releasers/terraform-module.ts

Fixes #794 and adds a new test case for the bug

fix: bug in Terraform version updater 

---

docs/manifest-releaser.md

docs: manifest releaser doc

---

docs/manifest-releaser.md

chore: manifest-releaser.md update

---

__snapshots__/manifest.js
src/manifest.ts

helps distinguish which PR is which if you release from multiple branches

feat(manifest): include default branch name in PR title

---

__snapshots__/dune-project.js
__snapshots__/ocaml.js
src/releasers/ocaml.ts
src/updaters/ocaml/dune-project.ts
test/updaters/dune-project.ts
test/updaters/fixtures/dune-project

Closes #864 
Closes #865 
Closes #866 🦕

fix(ocaml): Improve OCaml releaser for monorepos

---

src/github.ts

Stop using internal types, which sometimes prove to be flaky.

fix(octokit): address regression in internal octokit types

---

README.md

Fixes #778 🦕
I tried updating the README with the answers from #778. I hope this helps. Thanks so much for release-please!

docs: Add more detail around release process

---

__snapshots__/node.js
__snapshots__/package-lock-json.js
src/github.ts
src/releasers/node.ts
src/updaters/package-json.ts
src/updaters/package-lock-json.ts
test/manifest.ts
test/releasers/fixtures/node/npm-shrinkwrap.json
test/releasers/node.ts
test/updaters/fixtures/package-lock-v1.json
test/updaters/fixtures/package-lock-v2.json
test/updaters/package-lock-json.ts

Fixes #886
Fixes https://github.com/netlify/cli/issues/2082
> Opening in draft until I add some tests

feat(node): update npm-shrinkwrap file

---

src/github-release.ts
src/index.ts
test/github-release.ts

feat: allow overriding release label

---

__snapshots__/node-workspace.js
src/factory.ts
src/github.ts
src/manifest.ts
src/plugins/node-workspace.ts
src/release-pr.ts
src/releasers/java-bom.ts
src/releasers/java-yoshi.ts
src/updaters/java/java_update.ts
src/util/branch-name.ts
test/cli.ts
test/commit-split.ts
test/factory.ts
test/plugins/node-workspace.ts

fix(manifest): node-workspace plugin respects release-as

---

src/releasers/simple.ts

fix: update simple releaser for monorepo pkg path

---

docs/manifest-releaser.md

docs: fix typo

---

__snapshots__/go-yoshi.js
src/conventional-commits.ts
src/release-pr.ts
test/fixtures/pojos/commits-fix-scoped.json
test/fixtures/pojos/commits-release-as-scoped.json
test/releasers/go-yoshi.ts

fix(go-yoshi): Release-As should only apply to the correct file scope

---

src/github.ts
src/release-pr.ts

fix: switch searching for pending release PR to use pull request API

---

README.md
__snapshots__/cli.js
__snapshots__/krm-blueprint-version.js
__snapshots__/krm-blueprint.js
src/releasers/index.ts
src/releasers/krm-blueprint.ts
src/updaters/krm/krm-blueprint-version.ts
test/cli.ts
test/releasers/fixtures/krm/nested-pkg/nested/nested-project.yaml
test/releasers/fixtures/krm/nested-pkg/nested/nonKRM.yaml
test/releasers/fixtures/krm/nested-pkg/no-attrib-bucket.yaml
test/releasers/fixtures/krm/nested-pkg/project.yaml
test/releasers/fixtures/krm/simple-pkg/Kptfile
test/releasers/fixtures/krm/simple-pkg/README.md
test/releasers/fixtures/krm/simple-pkg/project.yaml
test/releasers/krm-blueprint.ts
test/releasers/utils.ts
test/updaters/fixtures/krm/multiKRMwithFn.yaml
test/updaters/fixtures/krm/simpleKRM.yaml
test/updaters/krm-blueprint-version.ts

feat: add krm-blueprint releaser

---

__snapshots__/go.js
src/releasers/go.ts

Default go releaser to updating CHANGELOG.md.
Fixes #924

feat(go): default to CHANGELOG.md

---

src/releasers/java-lts.ts
src/releasers/java-yoshi.ts
test/releasers/java-yoshi.ts

Fixes https://github.com/googleapis/repo-automation-bots/issues/2312

fix(java): find pre-release versions when looking for latestTag

---

src/errors/index.ts
src/github.ts
src/releasers/java-yoshi.ts
test/releasers/java-yoshi.ts

Refs: https://github.com/googleapis/repo-automation-bots/pull/2334 this change appears to cause issues for some of the releasers.
Reverts googleapis/release-please#982

Revert "fix(github-release): private repo not found error"

---

__snapshots__/manifest.js
__snapshots__/package-json.js
__snapshots__/php-yoshi.js
__snapshots__/root-composer.js
package.json
src/plugins/node-workspace.ts
src/updaters/ocaml/esy-json.ts
src/updaters/package-json.ts
src/updaters/php-manifest.ts
src/updaters/release-please-manifest.ts
src/updaters/root-composer.ts
src/updaters/samples-package-json.ts
src/util/json-stringify.ts
test/manifest.ts
test/plugins/node-workspace.ts
test/updaters/fixtures/package.json
test/updaters/package-json.ts
test/updaters/package-lock-json.ts
test/updaters/samples-package-json.ts
test/util/json-stringify.ts

Fixes #453 🦕
*(I don't understand why the tests don't pass on windows)*

feat: use original json's indentation and style

---

README.md
__snapshots__/cli.js
__snapshots__/elixir-mix-exs.js
__snapshots__/elixir.js
src/releasers/elixir.ts
src/releasers/index.ts
src/updaters/elixir-mix-exs.ts
test/cli.ts
test/releasers/elixir.ts
test/releasers/fixtures/elixir/mix.exs
test/updaters/elixir-mix-exs.ts
test/updaters/fixtures/mix.exs

feat: add elixir updater and releaser

---

src/releasers/python.ts
test/manifest.ts
test/releasers/python.ts

Fixes #1025 (eventually)
Some first pseudocodelike steps to fixing #1025. Untested.

feat(python): support packagename/__init__.py without pyproject.toml

---

.github/sync-repo-settings.yaml
README.md

https://github.com/googleapis/google-cloud-node/issues/3126

chore: switch to main branch

---

__snapshots__/node-workspace.js
docs/manifest-releaser.md
src/manifest.ts
src/plugins/node-workspace.ts
test/plugins/node-workspace.ts
typings/lerna__package-graph.d.ts

feat(manifest)!: force local linking in node-workspaces w/ config to disable

---

.github/release-please.yml
.github/sync-repo-settings.yaml
owlbot.py

build: configure branch 12.x as a release branch

---

src/versioning-strategy.ts

Small cosmetic fix, the name of the two updaters were not following of their class.

fix: set the version updater name accordingly

---

src/bin/release-please.ts

Pull request title pattern was not being passed to factory.

fix(cli): pass pull-request-title-pattern

---

__snapshots__/merge.js
src/plugins/merge.ts
test/helpers.ts
test/manifest.ts
test/plugins/merge.ts

fix: combined manifest PR should include labels

---

README.md
docs/cli.md
docs/customizing.md
docs/manifest-releaser.md
package.json
src/bin/release-please.ts

docs: update docs for v13

---

docs/customizing.md
src/versioning-strategies/always-bump-patch.ts
src/versioning-strategies/default.ts
src/versioning-strategies/dependency-manifest.ts
src/versioning-strategies/java-add-snapshot.ts
src/versioning-strategies/java-snapshot.ts
src/versioning-strategies/service-pack.ts
src/versioning-strategy.ts

docs: add docs for VersioningStrategy interfaces/implementations

---

__snapshots__/github.js
src/commit.ts
src/github.ts
src/manifest.ts
src/strategies/ruby-yoshi.ts
src/util/commit-split.ts
test/github.ts

fix: only backfill files if requested

---

src/github.ts
test/fixtures/pom-file-search-with-prefix.json
test/github.ts

fix: GitHub#findFilesByExtension should treat prefix as a directory

---

src/github.ts
src/manifest.ts
src/release.ts
src/strategies/base.ts
test/manifest.ts

fix: set the title when creating a release

---

README.md

docs: add README section on overriding commit message

---

docs/customizing.md
docs/manifest-releaser.md

docs: spelling and grammar fixes

---

docs/customizing.md

docs: fix generic update link error in docs/customizing.md

---

.repo-metadata.json

chore: update repo-metadata

---

__snapshots__/github.js
src/github.ts
test/github.ts

fix: pass target_commitish instead of sha

---

__snapshots__/go-yoshi.js
src/strategies/base.ts
src/strategies/go-yoshi.ts
src/strategies/php-yoshi.ts
src/strategies/ruby-yoshi.ts
src/strategies/ruby.ts
test/strategies/go-yoshi.ts

fix(go-yoshi): restore scope-based commit filtering

---

src/strategies/java-yoshi.ts
src/strategies/python.ts
src/strategies/terraform-module.ts
test/strategies/dart.ts
test/strategies/elixir.ts
test/strategies/java-yoshi.ts
test/strategies/node.ts
test/strategies/python.ts
test/strategies/terraform-module.ts

fix: search for files on target branch, not default branch

---

src/updaters/python/setup-py.ts

fix(python): fix version regex to find multiple digit patch versions

---

src/strategies/base.ts
src/strategies/node.ts
test/manifest.ts
test/strategies/dart.ts
test/strategies/helm.ts
test/strategies/node.ts

Read packageName from config if not provided.
Fixes #1264

fix: read packageName from config

---

src/plugins/cargo-workspace.ts
src/plugins/node-workspace.ts
src/plugins/workspace.ts
src/strategies/rust.ts
src/updaters/rust/cargo-lock.ts
test/plugins/cargo-workspace.ts
test/updaters/cargo-lock.ts

fix: cargo workspace cargo lock handling

---

src/strategies/base.ts
src/strategies/node.ts
test/strategies/node.ts

make pkgName property private.

refactor: make packageName private

---

__snapshots__/default-changelog-notes.js
__snapshots__/php-yoshi.js
src/strategies/php-yoshi.ts
test/changelog-notes/default-changelog-notes.ts
test/strategies/php-yoshi.ts

fix: php-yoshi strategy should handle custom changelog secctions

---

__snapshots__/manifest.js
src/manifest.ts
test/manifest.ts

fix: provide pull request to commit parser allow overrides

---

docs/cli.md
docs/customizing.md
docs/manifest-releaser.md

docs: add section on the format of a path

---

README.md

@chingor13 @Neenu1995  Adding FAQ of releasable units.

chore(doc): adding FAQ of the bot not creating PR

---

src/strategies/php-yoshi.ts
test/strategies/php-yoshi.ts

fix(php-yoshi): correctly ignore non-client directories

---

__snapshots__/base.js
__snapshots__/cli.js
docs/cli.md
docs/manifest-releaser.md
src/bin/release-please.ts
src/manifest.ts
src/strategies/base.ts
src/strategies/php-yoshi.ts
test/cli.ts
test/fixtures/manifest/config/changelog-host.json
test/manifest.ts
test/strategies/base.ts

feat: allow configure changelog-host

---

src/manifest.ts
test/manifest.ts

Towards https://github.com/googleapis/repo-automation-bots/issues/3649
If we cannot fetch the required manifest config files and a manifest has been requested, throw a `ConfigurationError` which is easier for downstream integrations to handle.

fix: throw ConfigurationError when required manifest config file is missing

---

src/factories/plugin-factory.ts
src/manifest.ts
src/plugins/cargo-workspace.ts
src/plugins/node-workspace.ts
src/plugins/workspace.ts
test/factories/plugin-factory.ts
test/plugins/node-workspace.ts

fix: workspace plugins should update manifest versions

---

__snapshots__/base.js
__snapshots__/default-changelog-notes.js
__snapshots__/linked-versions.js
__snapshots__/manifest.js
__snapshots__/rust.js
package.json

fix(deps): headings are now always H2

---

src/bin/release-please.ts
test/cli.ts

fix: set default bootstrap path to .

---

src/bin/release-please.ts
test/cli.ts

Fixes #1473 🦕 (thanks to the findings from @cbarrac)

fix: pass GitHub API URLs from options to builder

---

__snapshots__/ruby-yoshi.js
src/strategies/ruby-yoshi.ts

fix(ruby-yoshi): don't remove PR link from changelog

---

__snapshots__/changelog.js
src/strategies/dotnet-yoshi.ts
src/updaters/changelog.ts
test/updaters/changelog.ts
test/updaters/fixtures/CHANGELOG-dotnet.md

fix(dotnet-yoshi): autodetect component from path

fix(dotnet-yoshi): handle existing google-cloud-dotnet history format

---

.github/workflows/ci.yaml
package.json

Reverts googleapis/release-please#1489
Upstream `@octokit/types` fixed their regression

Revert "deps: temporarily pin `@octokit/types` to 6.37.0"

---

src/github.ts

Also adds debug logging to try to investigate failing graphql queries.
Fixes #1517

fix: stop iterating if we fail to receive commits from a graphql query

---

src/strategies/python.ts
test/strategies/python.ts

fix(python): Make __init__.py bump underscore / hyphen agnostic (#1525)

---

__snapshots__/github.js
src/github.ts
test/fixtures/merged-pull-requests-no-files.json
test/github.ts

fix: handles pull request iterator when graphQL returns no files

---

docs/manifest-releaser.md

This PR fixes a missing argument in the docs. I can open an issue for it if needed

fix(docs): Add missing `--repo-url` argument

---

schemas/config.json
src/manifest.ts
src/strategies/base.ts
src/strategies/java.ts
test/factory.ts
test/strategies/java.ts

feat: allow skipping snapshots for java strategies

---

.github/workflows/ci.yaml
package.json

Fixes #1557
deps: update octokit packages
deps: update code-suggester to v4

build!: drop node 12 support

---

docs/manifest-releaser.md
schemas/config.json
src/manifest.ts
test/fixtures/manifest/config/versioning.json
test/manifest.ts

feat: parse versioning type from the manifest config

---

.github/sync-repo-settings.yaml
.github/workflows/ci.yaml
package.json

Fixes #1557
deps: update octokit packages
deps: update code-suggester to v4

build!: drop node 12 support (#1563)

---

package.json

Includes the feature for splitting file updates into batches.

fix(deps): update code-suggester to 4.1.0

---

src/util/pull-request-title.ts
test/util/pull-request-title.ts

fix: allow parentheses in `pull-request-title-pattern`

---

__snapshots__/elixir-mix-exs.js
src/updaters/elixir/elixir-mix-exs.ts
test/updaters/elixir-mix-exs.ts
test/updaters/fixtures/mix-attribute.exs

Fixes #1030 comment 🦕
This adds support for updating an Elixir version that is set via a module attribute. This was [commented on in the original PR](https://github.com/googleapis/release-please/pull/1030#pullrequestreview-748505078) that added Elixir support but never acted on til now.

feat: update elixir version in module attribute

---

src/strategies/terraform-module.ts
test/strategies/terraform-module.ts

fix: detect uppercase readme.md files for TF

---

src/github.ts

fix: graphql proxy connection issue

---

__snapshots__/base.js
schemas/config.json
src/manifest.ts
src/strategies/base.ts
test/strategies/base.ts

feat: add initial version to base strategy

---

__snapshots__/python-file-with-version.js
src/updaters/python/python-file-with-version.ts
test/updaters/fixtures/version-with-long-patch.py
test/updaters/python-file-with-version.ts

fix(python): version updater updates patch versions >= 10

---

src/github.ts
src/manifest.ts
test/cli.ts
test/github.ts
test/manifest.ts
test/plugins/compatibility/linked-versions-workspace.ts
test/plugins/linked-versions.ts

Fixes #1645 🦕
NOTE: the code coverage seems to decrease, but I'm not familiar enough with the testing infrastructure to know how to address that. Any guidance would be appreciated.

feat: extract and return the created release id

---

docs/manifest-releaser.md

docs: add missing comma

---

package.json

fix(deps): update @google-automations/git-file-utils to 1.2.5

fix(deps): update code-suggester to 4.2.0

---

README.md
__snapshots__/cli.js
__snapshots__/sfdx-project-json.js
docs/customizing.md
src/factory.ts
src/strategies/salesforce.ts
src/updaters/salesforce/sfdx-project-json.ts
test/fixtures/strategies/salesforce/sfdx-project.json
test/strategies/salesforce.ts
test/updaters/fixtures/sfdx-project.json
test/updaters/salesforce.ts
test/updaters/sfdx-project-json.ts

feat: add Salesforce strategy

---

schemas/config.json

feat: add toml generic updater option to extra-files schema

---

docs/customizing.md

docs: add notes about `changelog-type` configuration

---

.eslintrc.json
src/plugins/cargo-workspace.ts
test/plugins/cargo-workspace.ts

fix(cargo-workspace): validate Cargo.toml version field

---

src/plugins/cargo-workspace.ts
test/plugins/cargo-workspace.ts
test/plugins/compatibility/linked-versions-workspace.ts

fix(cargo-workspace): find workspace modules on the target branch

---

__snapshots__/pom-xml.js
src/updaters/base-xml.ts
test/updaters/fixtures/pom-trailing-newline.xml
test/updaters/pom-xml.ts

fix(xml): preserve trailing newline if the xml file had one

---

README.md

@chingor13 @diegomarquezp @rajatbhatta, Shall we add the explanation of "autorelease: pending" label explanation for Release Please troubleshooting?

docs: troubleshooting with "autorelease: pending" label

---

docs/manifest-releaser.md

fix invalid json in the manifest-releaser.md

docs(manifest-releaser): fix typos

---

.github/workflows/ci.yaml
package.json

Use `--no-experimental-fetch` node option for node 18

test: also test on node 18

---

package-lock.json

Lockfile is for development, and these semver deps are transitive deps

chore(deps): bump semver dependencies in lockfile

---

.kokoro/release/publish.cfg
owlbot.py

The Kokoro image was trying to build with node 14.

build: release on node 18

---

docs/customizing.md

docs: fix versioning strategy table rendering

---

__snapshots__/package-json.js
src/updaters/node/package-json.ts

fix: old version range detection

---

release-please-config.json

owlbot post processor messed up this config in this repo

build: restore extra-files config

---

README.md
__snapshots__/cli.js
__snapshots__/module-bazel.js
src/factory.ts
src/strategies/bazel.ts
src/updaters/bazel/module-bazel.ts
test/strategies/bazel.ts
test/updaters/fixtures/MODULE-inline.bazel
test/updaters/fixtures/MODULE-missing.bazel
test/updaters/fixtures/MODULE-order.bazel
test/updaters/fixtures/MODULE.bazel
test/updaters/module-bazel.ts

feat: add support for `bazel`

---

src/manifest.ts

fix: respect signoff in config

---

src/manifest.ts

the `:robot:` is replaced with 🤖  intentionally. Otherwise the trailing colon must be removed
Fixes #2347 🦕

fix: fix comment at release pr is ugly

---

schemas/config.json

A follow up of https://github.com/googleapis/release-please/pull/2227
Fixes #2340  🦕

chore: add missing generic updaters in to release please config schema extraFiles

---

src/updaters/changelog-json.ts

Fixes small typo in `src/updaters/changelog-json.ts`

docs: fix typo in src/updaters/changelog-json.ts

---

src/github.ts
test/github.ts

The node-workspace plugin's manifest file update was overwriting the default change made in manifest.ts with no changes.
This resolves the problem of Release Please not updating the manifest file in https://github.com/googleapis/gcloud-mcp/pull/204/files.
b/444669596

fix: merge updates when creating a changeset
