package.json, src/bin/release-please.ts, src/github.ts, src/mint-release.ts
Add a label (defaulting to `autorelease: pending`) to the PRs generated by `release-please`, this should allow our existing auto-release machinery to take over.
We should be able to perform end-to-end testing once https://github.com/googleapis/releasetool/pull/181 is released.
=> feat: add a label to the release PR for automation

src/bin/release-please.ts, src/conventional-commits.ts, src/mint-release.ts, test/conventional-commits.ts
By default a breaking change will now always bump the semver major, unless you run with `--bump-monor-pre-major`.
BREAKING CHANGE: prior to this the minor was bumped rather than major for pre-major releases
=> feat: you must now opt in to bumping minor pre-major

.github/action/mint-release/Dockerfile, .github/action/mint-release/check.js, .github/main.workflow
Releases will only be created if a comment is added by a user in a Googley org, and if the comment is made on the appropriate issue.
=> build: apply ACL to the creation of releases

src/bin/release-please.ts, src/candidate-issue.ts, src/github.ts, system-test/github.ts
This PR adds the command for generating candidate releases, [one pictured here](https://github.com/googleapis/release-please/issues/65)
The idea is that these candidate releases demonstrate what the release would look like, and by commenting on the issue a PR for the release actually gets created -- updating CHANGELOG, pertinent files, etc.
=> feat: adds command for creating candidate releases

src/bin/release-please.ts, src/candidate-issue.ts, src/github.ts, src/mint-release.ts, system-test/github.ts
based on @alexander-fenster's recommendation I've simplified the design significantly; to create a release you now just click on a checkbox:
=> feat: checkbox based releases

package.json, src/bin/release-please.ts, src/candidate-issue.ts, src/github.ts, src/release-pr.ts
`MintRelease` does not facilitate an entire release, rather it opens the PR for a release (I'm starting work on the next step called GitHub release, which actually creates the release with the GitHub API).
=> refactor: `MintRelease` is better described as `ReleasePR`

src/bin/release-please.ts
added a helper for generating GitHub action, this should go in `.github/main.workflow`.
=> feat: add command for generating action config

__snapshots__/candidate-issue.js, src/candidate-issue.ts, test/candidate-issue.ts
when a PR is created from a candidate issue, we replace the `[x]` with a link to the PR that was created (this is neat) ... *but* when the bot comes back around and updates the candidate issue, we overwrite the updated footer with an empty checkbox.
This PR introduces a footer comment, which is used to avoid updating the candidate issue until the PR generated is landed.
=> feat: don't remove link to PR until new commits landed

.github/main.workflow, package-lock.json, src/bin/release-please.ts, src/candidate-issue.ts, src/github.ts, src/release-pr.ts, system-test/github.ts
breaking candidate-issue into two commands:
`candidate-issue` and `detect-checked-issue`;
This will allow us to run the less expensive (in terms of API calls) checkbox check more frequently as a cron, and the expensive `candidate-issue` which updates a candidate issue less frequently.
=> feat: introduce detect-checked command, a quick check for whether a release has been requested

.kokoro/samples-test.sh, .kokoro/system-test.sh, .kokoro/test.sh
codecov's docs claim that coverage should be merged across multiple test runs for a build, let's test this, and see if we can bump our coverage up a bit.
=> test: testing codecov's claim that they merge coverage

package-lock.json, src/bin/release-please.ts, src/candidate-issue.ts, src/github-release.ts, src/github.ts, src/release-pr.ts, system-test/github.ts
This reworks the ReleasePR logic, such that it could be invoked whenever a PR is merged, and keep a candidate release issue up-to-date. Mainly it:
- ~[x] switches to checking for a `latestRelease` before falling back to looking up tags (my hope being that this will be a cheaper operation, and eliminates bugs related to tags on branches).~ it turns out `latestRelease` does not include an appropriate git sha, so holding off on this functionality for now.
=> refactor: reworked release-pr logic, to work better in isolation

package-lock.json, src/github.ts, src/release-pr.ts, system-test/github.ts
To test this, I also had to fix a bug with how we were comparing labels; we should ensure all labels match on the PR, not just one of them.
=> fix: if we generate a CHANGELOG with only a header, don't open a PR

__snapshots__/github-release.js, src/github-release.ts, test/fixtures/CHANGELOG-bug-140.md, test/github-release.ts
=> fix: extend release notes regex to support patches

package-lock.json, src/github.ts, src/release-pr.ts, system-test/github.ts
Now looks for an existing PR with the same ref before creating a new PR.
fixes: #141, #128
=> fix: force update branch rather than closing and reopening PRs

__snapshots__/samples-package-json.js, package-lock.json, test/updaters/fixtures/samples-package.json
We don't really use it anymore, so I'm trying to eliminate all traces.
=> chore: remove nodejs-repo-tools

.github/action/release-please/Dockerfile, .github/action/release-please/entrypoint.sh, src/bin/release-please.ts, src/github.ts
Running the action on every commit seems to kick off too many actions, and leads to race conditions. Let's instead kick off the action when a PR is merged.
=> feat!: update GitHub action to run on PR rather than commit

.kokoro/continuous/node10/system-test.cfg, .kokoro/presubmit/node10/system-test.cfg, .kokoro/system-test.sh, synth.py, system-test/github.ts, test/release-pr.ts
Get integration tests at least working:
Notes:
* I would like to come back and revisit the actual shape of the integration tests, as I don't find them super useful right now (regardless I'd like to have them passing).
* I've been using release-please to test the new magic-proxy based configuration, so for the time being I have some `.kokoro` files excluded from test runs. I will remove these exclude rules once a mass PR is made for the `.kokoro` updates.
=> test: get integration tests working again

__snapshots__/release-pr.js, package-lock.json, src/github.ts, src/release-pr.ts
currently, whenever we land a PR we update a release PR, even if there have been no additional changes.
fixes #158
=> feat: avoid updating release PR if no additional changes

__snapshots__/changelog.js, __snapshots__/github-release.js, __snapshots__/release-pr.js, package-lock.json, src/bin/release-please.ts, src/github-release.ts, src/github.ts, src/release-pr.ts, src/updaters/changelog.ts, src/updaters/package-json.ts, src/updaters/php-class-versions.ts, src/updaters/php-client-version.ts, src/updaters/php-manifest.ts, src/updaters/root-composer.ts, src/updaters/samples-package-json.ts, src/updaters/update.ts, test/fixtures/CHANGELOG-php-yoshi.md, test/github-release.ts, test/release-pr.ts
* PHPClientVersion: updates the `const version` in client libraries.
* PHPManifest: adds new version to array in manifest.
* RootComposer: adds updated version to root composer file.
=> feat: adds additional updaters/logic for PHP mono-repo

src/github.ts, test/release-pr.ts
hadn't planned on a mono-repo which might keep the PR open long enough for it to float down below 25 recent commits (our release PR was the 27th or so most recent commit).
I believe pulling this out to 100 would have covered us pretty well.
=> fix: increase PRs checked during release to 100

__snapshots__/graphql-to-commits.js, __snapshots__/java-auth-readme.js, __snapshots__/java-auth-versions.js, __snapshots__/pom-xml.js, src/bin/release-please.ts, src/github.ts, src/graphql-to-commits.ts, src/release-pr.ts, src/updaters/java-auth-readme.ts, src/updaters/java-auth-versions.ts, src/updaters/pom-xml.ts, test/fixtures/commits-with-labels.json, test/graphql-to-commits.ts, test/updaters/fixtures/java-auth-readme.md, test/updaters/fixtures/java-auth-versions.txt, test/updaters/fixtures/pom.xml, test/updaters/java-auth-readme.ts, test/updaters/java-auth-versions.ts, test/updaters/pom-xml.ts
Adds support for the files that should be updated during a release of `google-auth-library-java` (_this represents a good prototype of what things will look like once the repo split happens for Java_).
New updaters added:
* `versions.txt`: for normal releases updates all entries to `version:version`, for snapshot releases updates entries to `previous-release:snapshot-release`.
* `pom.xml`: update to `<version>newVersion</version>`.
* `README.md`: update examples of Java, Scala, and Groovy imports.
@chingor13 please take a look and let me know if the logic looks right, tomorrow I'll actually integrate it with the CLI and we can play around.
=> feat: adding support for google-auth-library-java

.gitignore, src/bin/release-please.ts, src/updaters/samples-package-json.ts, test/updaters/samples-package-json.ts
oktokit includes auth headers and URL in the error object, this makes printing the error object a security concern.
=> fix: don't print full error in --debug mode

__snapshots__/commit-split.js, __snapshots__/github.js, __snapshots__/graphql-to-commits.js, __snapshots__/release-pr.js, src/conventional-commits.ts, test/fixtures/commits-yoshi-php-monorepo.json
Our PHP team expects that the minor version would be bumped for new features pre 1.x.x, seems reasonable to me.
=> fix: reflect yoshi's use of minor version bumps

src/conventional-commits.ts, src/github.ts, src/releasers/ruby-yoshi.ts, test/release-pr.ts
1. we now check the last 100 PRs, when deciding whether to close stale PRs.
2. we now show a "Documentation" section in changelog: only with one entry for all docs, only if at least one docs change exists.
3. our logic for updating `version.rb` was slightly off (it needed to replace `-` with `/`).
=> fix: address bugs found during first run on Ruby

__snapshots__/pom-xml.js, src/updaters/java/pom-xml.ts, test/updaters/fixtures/pom.xml
=> fix: replace all version update tags

__snapshots__/java-yoshi.js, src/github.ts, src/releasers/java-yoshi.ts, src/updaters/java/versions-manifest.ts, test/releasers/fixtures/README.md, test/releasers/fixtures/commits-yoshi-java.json, test/releasers/fixtures/pom.xml, test/releasers/fixtures/versions.txt, test/releasers/java-yoshi.ts
In Java, we allow an extra qualifier type to the semver which should be preserved across version bumps:
i.e. 0.1.2-beta -> minor bump -> 0.2.0-beta
=> feat: java-specific version bumping

__snapshots__/java-yoshi.js, src/releasers/java-yoshi.ts, test/releasers/fixtures/released-versions.txt, test/releasers/java-yoshi.ts
=> fix(java): snapshot bumps should not autorelease

src/bin/release-please.ts, src/release-pr-factory.ts, src/release-pr.ts, src/releasers/ruby.ts
I have not tested this yet, but I think it should work for Ruby applications, it introduces additional config option `versionFile`, which we are going to use to point to `version.rb` (which has a location that can be difficult to infer in a project).
=> feat: add strategy for non-mono-repo Ruby releases

src/releasers/java-yoshi.ts
we're periodically seeing snapshots fail to update for Java, I'm suspicious it's a caching issue when fetching content.
CC: @codyoss, @kolea2
=> feat(logging): add logging to track Java snapshot bug

src/graphql-to-commits.ts
I found an edge-case on one of my repos, such that `prEdge.node.mergeCommit` was `null`.
=> fix: handle null prEdge.node.mergeCommit

src/graphql-to-commits.ts
bumped into edge-case fetching files from graphql, this functionality is only used by mono-repos.
=> fix: in some cases prEdge.node.number can reference missing data

src/releasers/php-yoshi.ts
Fixes #348.
Hello friends! This change aims to cause release-please to include `chore` and `docs` changes in our changelog, and therefore to cause those types of changes to be released, even if no other changes have been made to a given component.
I followed the relevant portions of #238, where @bcoe added a similar feature to the ruby releaser. I looked through the test suites and did not find anything which seemed to relate closely to this part of the application, but if I missed something, please let me know and I'll work to fix it!
Thanks for considering the change. :)
=> feat: include docs and chores in PHP releases and changelogs

package.json, src/github.ts, src/release-pr.ts
there were breaking TypeScript changes in the last release of octokit, trying to get us on a similar version across our libraries.
=> chore: switch to newest version of octokit dependencies

__snapshots__/java-yoshi.js, src/github.ts, src/release-pr.ts, test/github.ts
let's just close open issues with `autorelease: pending` by default, `process` is used too commonly.
=> fix: process label was causing PRs to be closed

src/releasers/php-yoshi.ts
Follows up on #352, adds custom changelog sections to component changeset.
=> fix: support changelog types for PHP components

src/release-pr.ts, test/release-pr.ts
If additional content followed the special `release-as:` footer, we were not parsing it.
This fix should address the issue observed [here](https://github.com/googleapis/python-spanner/pull/37).
CC: @skuruppu
=> fix: handle additional content after release-as: footer

package.json, src/bin/release-please.ts, tsconfig.json
yikes, we have a bad publication because we weren't compiling `bin` with the new config, we should add integration tests to catch this in the future.
=> fix: we were not compiling src/bin

src/release-pr.ts, synth.py
=> fix: delay snapshots temporarily

src/releasers/java-yoshi.ts, test/releasers/java-yoshi.ts
snapshot releases were pinning at ancient SHAs in some cases, because we use the last tag rather than the latest commit at head.
We now use the latest commit at head.
=> fix: snapshots will now be taken from the latest commit

__snapshots__/conventional-commits.js, src/conventional-commits.ts, test/conventional-commits.ts
Introduces a mechanism for performing some cleanup after the conventional commit parse. In this case we stop reading a BREAKING CHANGE comment after two newlines, to prevent:
https://github.com/googleapis/nodejs-logging/commit/ce29b498ebb357403c093053d1b9989f1a56f5af
=> fix: stop parsing BREAKING CHANGE message after two newlines

src/releasers/java-yoshi.ts
=> fix(java): logging message should not crash when there's no latestTag

__snapshots__/java-bom.js, src/github.ts, test/github.ts
pre-releases were being used in the logic for calculating the latest tag, this meant that as soon as we released a pre-release, it broke the CHANGELOG generation on the next run.
=> fix: don't include pre-release in latestTag calculation

src/github-release.ts, src/github.ts, test/github-release.ts
by returning the release created, we can use this value as output in a GitHub action [see](https://github.com/bcoe/release-please-action/issues/8).
=> feat: return the release created by createRelease()

__snapshots__/release-pr-factory.js, src/release-pr-factory.ts, src/releasers/index.ts, test/release-pr-factory.ts
The GitHub action I've been working on uses WebPack for shipping (which is a suggested best practice), by moving our factory to being dynamic, this broke WebPack.
This PR leaves the dynamic factory (this is reasonable to have as we've been tending to add helpers for yoshi/google specific library structures, and this reduces the number of steps for doing so), but introduces a static factory helper for fetching classes which are likely to be used by the wider community.
=> feat: introduce static factory helper

__snapshots__/java-yoshi.js, __snapshots__/simple.js, src/github.ts, src/releasers/simple.ts, src/updaters/changelog.ts, src/updaters/java/google-utils.ts, src/updaters/java/java_update.ts, src/updaters/package-json.ts, src/updaters/php-client-version.ts, src/updaters/php-manifest.ts, src/updaters/python/setup-cfg.ts, src/updaters/python/setup-py.ts, src/updaters/root-composer.ts, src/updaters/samples-package-json.ts, src/updaters/terraform/readme.ts, src/updaters/update.ts, src/updaters/version-rb.ts, src/updaters/version-txt.ts, src/updaters/version.ts, test/releasers/java-yoshi.ts, test/releasers/simple.ts
Instead of making assumptions such as "let's run / let's not run CI for the first / the last / whatever file", let's just make it configurable. I'm only using this flag in the simple releaser but any other releaser can be upgraded if needed. The default behavior is `skipCi: true` so nothing is changed for other releasers.
=> feat: a flag to skip CI

src/graphql-to-commits.ts, test/fixtures/commits-with-labels.json
For merge commits, prEdge.node.mergeCommit.oid references the SHA of the
commit at the top of the list of commits, vs., its own SHA. We track the
SHAs observed, and if the commit references a SHA from earlier in the list
of commitHistory.edges being processed, we accept it as a valid commit.
=> fix: merge commits now handled

src/releasers/java-yoshi.ts, test/releasers/java-yoshi.ts
This will allow release-please to handle repos like gax-java and other gradle projects we manage
=> feat(java-yoshi): handle build.gradle and dependencies.properties files

src/releasers/python.ts
=> fix: list commits of type `docs` for python

__snapshots__/node.js, src/releasers/node.ts, test/releasers/fixtures/node/commits.json, test/releasers/fixtures/node/package-lock.json, test/releasers/fixtures/node/package.json, test/releasers/node.ts
Keep version number in package-lock.json in sync with package.json.
Fixes #464
I had some time to kill so I thought I would implement this PR despite the issue still being in triage.  I know there is a chance that updating `package-lock.json` isn't the desired behavior, but I did have some time to kill and understand if issue #464 and this PR are declined.
=> feat(node): update version number in package-lock.json

src/release-pr.ts, src/releasers/java-auth-yoshi.ts, src/releasers/java-bom.ts, src/releasers/java-yoshi.ts, test/releasers/java-bom.ts, test/releasers/java-yoshi.ts, test/releasers/node.ts
releasers now need to indicate that they support nightly snapshot builds, before they will start running.
=> feat(snapshot): skip snapshot releases for releasers that lack this concept

src/releasers/java-bom.ts, src/releasers/java-yoshi.ts
This logic was not working any ways, now that we're configuring a nightly cron, let's move away from it.
=> refactor(snapshot): do not delay before running snapshot logic

src/releasers/java-bom.ts, src/releasers/java-yoshi.ts, test/releasers/java-bom.ts, test/releasers/java-yoshi.ts
`snapshot` is a `boolean?` on release-pr. This changes the behavior such that if you specify `snapshot`, we will now ensure that only that type of release is created.
If you don't provide `snapshot` (i.e. it is undefined), then we will detect whatever state the repo is in and propose the correct release accordingly.
=> fix: skip Java releases if snapshot is specified, but does not match repo state

src/releasers/java-auth-yoshi.ts, src/releasers/java-bom.ts, src/releasers/java-yoshi.ts
Noticed this in logs when we were testing the new nightly cron.
=> fix: exception was thrown when 0 commits found

src/github.ts
Octokit seems to expect headers (including authorization) to be passed along with the repo and owner params. The issue is described in #474.
Fixes #474 🦕
=> fix: missing authorization header for repos.get()

__snapshots__/node.js, src/releasers/node.ts
By moving files that are required updates to the end of the update loop, like `package.json`, we guarantee that at least one commit will be added that forces CI/CD.
=> fix(node): reorder files added, so that skip logic works

__snapshots__/java-yoshi.js, __snapshots__/node.js, __snapshots__/simple.js, src/github.ts
@ghermeto pointed out we weren't using conventional commit messages for our own commit messages.
Let's do so. After talking to Guilherme, we've opted for `chore:`.
=> fix: use conventional commits for our own commits

README.md, __snapshots__/node.js, src/bin/release-please.ts, src/github-release.ts, src/github.ts, src/release-pr.ts, src/releasers/java-auth-yoshi.ts, src/releasers/java-bom.ts, src/releasers/java-yoshi.ts, src/releasers/node.ts, src/releasers/php-yoshi.ts, src/releasers/python.ts, src/releasers/ruby-yoshi.ts, src/releasers/ruby.ts, src/releasers/simple.ts, src/releasers/terraform-module.ts, test/releasers/node.ts
This PR adds support for releasing libraries from a folder other than a repository's root:
You can now set the option `--path` which represents the path that package lives in, e.g., `--path packages/gcf-utils`.
You can also set the flag `--monorepo-tags`, which will prepend the library name to release branches and tags  (this allows you to release multiple libraries from one repository (see: https://github.com/bcoe/test-release-please/pull/43).
=> feat: add support for monorepos/releasing from alternate folders

__snapshots__/java-yoshi.js, src/releasers/java-bom.ts, src/releasers/java-yoshi.ts, test/releasers/fixtures/java-yoshi/empty-commits.json, test/releasers/java-yoshi.ts
Handles the case where there have been no new commits since the last release, and the snapshot cron executes.
_Note: @chingor13 I notice that [this snapshot](https://github.com/googleapis/java-storage/pull/432) was created, does this mean that our cron is working as long as the latest release isn't the most recent?_
Fixes #500
=> fix(java-snapshot): handle no new commits since release

__snapshots__/yoshi-go.js, package.json, src/conventional-commits.ts, src/releasers/go-yoshi.ts, test/releasers/fixtures/yoshi-go/commits.json, test/releasers/yoshi-go.ts
This adds support for releasing the Yoshi gapic go libraries.
TODO:
Future Work:
* figure out the manual yoshi libraries.
CC: @codyoss
=> feat(go): add support for releasing yoshi gapic go libraries

__snapshots__/yoshi-go.js, src/releasers/go-yoshi.ts, test/releasers/fixtures/yoshi-go/commits.json
The scope matching was too greedy and caught things like
"pubsublite". Scope should be an exact match or be within the same
directory structure.
=> fix(go): Update scope matching and regen regex

__snapshots__/yoshi-go.js, src/releasers/go-yoshi.ts
If the first commit was of the `all` type, we were setting its sha to `null`, this meant we had no sha to base a commit on.
=> fix(yoshi-go): store the sha of the first commit

src/bin/release-please.ts, src/github-release.ts
Allow CHANGELOG path to  be configured, so that go can have an alternate name.
=> feat: allow CHANGELOG path to be  set

src/release-pr.ts
The regex for `release-as` now supports pre-releases, e.g., `v1.0.0-foo.0`.
=> feat(release-as): release-as now supports pre-release

src/releasers/simple.ts, src/updaters/version-txt.ts, test/release-pr-factory.ts, test/releasers/simple.ts
there's no reason we can't just create the `version.txt` if it doesn't exist.
=> fix(simple): create version.txt if it does not exist

src/release-pr.ts, src/releasers/node.ts, src/releasers/python.ts, src/releasers/ruby.ts, src/releasers/simple.ts, src/releasers/terraform-module.ts
=> feat:  pass an array of change log section options to the node releaser

src/github.ts
0 now represents a pull request that requires no updates.
=> fix: return 0 rather than -1 if PR not found

package.json, src/github.ts
forking does not work in the context of a GitHub Action. Let's turn off the functionality for now.
_Note: dependent on work happening in code-suggester that's not landed yet._
=> fix: forks do not work for GitHub Actions or apps

src/github.ts, src/release-pr.ts, test/github.ts, test/release-pr.ts
This adds support for pre-releases, prior to the first major version of the library being shipped (_v1.0.0-alpha1_, `v1.0.0-alpha2`, etc).
This is for the benefit of `dotnet` which uses this approach.
=> feat: initial support for pre-releases

test/github-release.ts, test/release-pr.ts, test/releasers/java-yoshi.ts, test/releasers/node.ts
A dependency somewhere in the tree started expecting that `/` be encoded as `%2F` when fetching contents from GitHub.
=> test: a dependency now expects / encoded as %2F

src/github.ts
Fix for a bug found in the work for https://github.com/googleapis/release-please/issues/428
=> fix: sort commits from graphql output by descending commit date so we get fresh results

src/github.ts
When merging @feywind's logic with my logic for pagination, it looks like the pagination and branch info were left in the wrong portion of the graphql query.
=> fix: pagination logic broken in merge

src/release-pr-factory.ts, src/release-pr.ts
Needed so that the GitHub Action can invoke the Ruby releaser.
=> feat: Support the Ruby releaser from the static ReleasePRFactory

__snapshots__/github-release.js, __snapshots__/yoshi-go.js, src/bin/release-please.ts, src/github-release.ts, src/github.ts, src/release-pr.ts, src/releasers/go-yoshi-submodule.ts, src/releasers/go-yoshi.ts, test/github-release.ts, test/github.ts, test/releasers/yoshi-go.ts
Makes `github-release` able to handle mono-repos, when `monorepo-tags` is set to `true`.
=> feat(go): add support for mono-repo google-cloud-go repo

package.json, src/releasers/go-yoshi-submodule.ts, src/releasers/go-yoshi.ts
We were looking for a `-` suffix in the go releaser and should not be.
=> fix(go): we should not include - in the suffix

src/github.ts, src/release-pr.ts, test/release-pr.ts
Do not include the `@foo/` prefix in the branch name selected for Node.js monorepos.
=> fix(nodejs): do not include org in branch name

__snapshots__/conventional-commits.js, src/conventional-commits.ts, test/conventional-commits.ts
Include multiline breaking changes, unless separated by two lines.
Fixes #440
=> fix: include multi-line breaking changes

__snapshots__/module-version.js, __snapshots__/terraform-module.js, src/releasers/terraform-module.ts, src/updaters/terraform/module-version.ts, test/releasers/fixtures/terraform/module-no-versions/main.tf, test/releasers/fixtures/terraform/module-no-versions/readme.md, test/releasers/fixtures/terraform/module-no-versions/versions.tf, test/releasers/fixtures/terraform/module-submodule/main.tf, test/releasers/fixtures/terraform/module-submodule/modules/sub-module-missing-versions/main.tf, test/releasers/fixtures/terraform/module-submodule/modules/sub-module-missing-versions/readme.md, test/releasers/fixtures/terraform/module-submodule/modules/sub-module-with-version/main.tf, test/releasers/fixtures/terraform/module-submodule/modules/sub-module-with-version/readme.md, test/releasers/fixtures/terraform/module-submodule/modules/sub-module-with-version/versions.tf, test/releasers/fixtures/terraform/module-submodule/readme.md, test/releasers/fixtures/terraform/module-submodule/versions.tf, test/releasers/fixtures/terraform/simple-module/main.tf, test/releasers/fixtures/terraform/simple-module/readme.md, test/releasers/fixtures/terraform/simple-module/versions.tf, test/releasers/terraform-module.ts, test/updaters/fixtures/versions.tf, test/updaters/module-version.ts
=> feat: Add TF versions updater

src/releasers/go-yoshi.ts
This crops up in the GitHub APP, which passes in the authenticated instance from probbot.
=> fix: pass gh instance to submodule

__snapshots__/github-release.js, src/github-release.ts, test/github-release.ts
Allow path to be provided in conjunction with `monorepoTags`, indicating that submodules are released from a nested path, e.g.,
`src/apis/*`
=> feat(monorepos): support submodules in nested folders

__snapshots__/github-release.js, src/github-release.ts, src/github.ts, test/github-release.ts
To configure GitHub releases on a monorepo, it is now expected that you provide: packageName (used to lookup branch name); path (used to specify folder; monorepo-tags (true indicates a monorepo release).
---
This is a less magical implementation of monorepo support for creating GitHub releases. Rather than handling multiple release PRs at once (across multiple submodules in a project), it's now expected that you set `path` and `packageName` to indicate the submodule the release is running for.
It's assumed that you would use a GitHub action to detect changes to specific folders, and run this command appropriately.
=> feat(github-release)!: packageName now used to specify submodule

src/github-release.ts, test/github-release.ts
Return major/minor/patch information in output from creating a GitHub release, this can in turn be chained into another action which pushes a tag.
Refs https://github.com/google-github-actions/release-please-action/issues/91
=> feat!: return major/minor/patch when creating GitHub release

src/bin/release-please.ts, src/release-pr.ts
This will allow the forking version of relese-please to run with less permissions enabled.
=> feat: allow cleanup steps to be turned off

src/release-pr.ts
Forks do not have permission to label.
=> fix: do not add labels when running on fork

src/bin/release-please.ts, src/release-pr.ts
The reason for clean was to avoid running certain operations from a fork, we can use the fork option for this instead.
=> revert!: reverts adding clean option

__snapshots__/conventional-commits.js, src/conventional-commits.ts, test/conventional-commits.ts
Adds support for the parsing extension proposed by the googleapis repository.
---
@JustinBeckwith I was mistaken about markdown being stripped out during rendering, I'm open to trying out this approach; if you think it's worth providing customers with the additional context?
=> feat(conventional-commits): support googleapis extension

package.json, src/github.ts, src/graphql-to-commits.ts
I no longer remember why we were throwing out commits if their oid did not match the top level oid, and this was breaking repos that use a merge commit flow.
=> fix: logic was throwing out merge commits

src/release-pr.ts, src/releasers/go-yoshi.ts
The cleanup step was closing the submodule releases, leading to more PRs being opened and closed then should be necessary.
=> fix: do not close stale PRs for submodules

src/github.ts, src/releasers/ruby.ts, test/github.ts
This switches to the same tagging scheme as go for ruby monorepos, which is what [google-api-ruby-client](https://github.com/googleapis/google-api-ruby-client) was assuming.
=> fix(ruby): use same tagging scheme as go

__snapshots__/yoshi-go.js, src/releasers/go-yoshi.ts, test/releasers/yoshi-go.ts
we were skipping passing `monorepoTags` with our more complicated approach.
=> fix(go): pass monorepo-tags to open-pr; omit commits when publishing gapic submodule

__snapshots__/yoshi-go.js, src/releasers/go-yoshi.ts, test/releasers/fixtures/yoshi-go/cloud-go-commits.json
* GAPIC/Apiary should always bump `minor`.
* submodules should bump `fix`, if only fixes have occurred.
☝️ we should probably break this out into a separate setting eventually, if we want this to be useful to more generic go repositories.
=> fix(go): submodules should bump patch

src/release-pr-factory.ts, src/releasers/index.ts
Our approach of dynamically loading releasers does not work well for webpack, and therefore can break the GitHub actions which uses rollup.
=> fix(webpack): make release-please webpackable

__snapshots__/yoshi-go.js, package.json, src/conventional-commits.ts, test/helpers.ts, test/releasers/yoshi-go.ts
* moves to new [@conventional-commits/parser](https://www.npmjs.com/package/@conventional-commits/parser): eliminating the need for stream-based parsing, simplifying the code, and giving us more flexibility to add our own custom functionality to the parser.
* pulls in latest version of `conventional-changelog-writer` which fixes #601.
* drop `conventional-commits-parser` dependency.
Fixes #601 
Refs #581
=> refactor: migrate to @conventional-commits/parser and update conventional-changelog

src/github.ts, src/releasers/go-yoshi.ts, src/releasers/ruby.ts, test/github.ts
Investigating moving a lerna project over to release-please, I noticed that tags have the `@` suffix rather than `-`. There have been a couple other languages that use releasa-please where the tags use `/`, rather than `-`.
Instead of making each of these a special case, this PR checks each suffix, this will make it easier to migrate to release-please from other tools.
=> feat: support @ and / when falling back to tags

__snapshots__/github-release.js, src/github-release.ts, src/github.ts, src/release-pr.ts, src/releasers/node.ts, src/util/package-branch-prefix.ts, test/github-release.ts, test/release-pr.ts, test/releasers/node.ts, test/util/package-branch-prefix.ts
fixes a couple of issues:
1. if node releaser doesn't specify packageName then github-release
wasn't filtering merged PRs correctly.
2. when solving the above, we need to be consistent about the
relationship between packageName and the release branch name.
Fixes #668
=> fix(monorepos): github-release not created

src/github-release.ts, test/github-release.ts
In monorepos there's enough traffic on PRs that looking at the last 25 didn't catch a release.
=> fix(github-release): increasae page size finding release

src/github-release.ts, src/github.ts, test/github.ts, test/release-pr-factory.ts, test/release-pr.ts, test/releasers/java-bom.ts, test/releasers/java-yoshi.ts, test/releasers/node.ts, test/releasers/yoshi-go.ts
There's a danger that someone comments on an old merged release PR, brining it earlier in chronological order, this would mean that we attempt to re-release the same version given how last release is calculated.
This is not a problem when tagging a release, which only occurs once after a PR is merged.
=> fix(pagination): when tagging release, use updated, vs., created

__snapshots__/github.js, __snapshots__/java-bom.js, __snapshots__/java-yoshi.js, src/release-pr.ts, test/github.ts, test/releasers/java-bom.ts, test/releasers/java-yoshi.ts
The nock mocks make it hard to follow and are deeply tied to the GitHub implementation.
=> test(java): convert Java releaser tests to use sinon

src/releasers/go-yoshi.ts
This logic is now being handled by setting
`bumpMinorPreMajor` to true.
=> chore(go): cleanup unused code

src/github.ts, test/github-release.ts, test/release-pr-factory.ts, test/release-pr.ts, test/releasers/node.ts, test/releasers/yoshi-go.ts
This breaks the packaged version of the library.
Reverts googleapis/release-please#715
=> Revert "fix: use resolove to find imports in tests"

__snapshots__/github.js, src/github-release.ts, src/github.ts, test/github-release.ts, test/github.ts
This will allow us to pass `""` as the `packageName` in order to tag releases where we do not want to include the package name. (The release title will just be the version)
=> feat: allow explicitly empty packageName when creating a release

src/github.ts, src/release-pr.ts
`GitHub.openPR` is version agnostic. Callers are responsible for embedding
version information however they see fit into the components of a PR
It also does not need to know about any particular sha as its sole job
is to create or update a releasePR with the provided changes.
=> refactor(github): unused GitHubPR properties

__snapshots__/github.js, src/github.ts, test/fixtures/commits-since-page-1.json, test/fixtures/commits-since-page-2.json, test/fixtures/commits-since.json, test/fixtures/latest-tag-alternate-branch.json, test/fixtures/latest-tag-monorepo.json, test/fixtures/latest-tag-no-commits.json, test/fixtures/latest-tag.json, test/github.ts
Adds a GraphQL query that looks at commits to the current branch and iterates/pages through them to find a commit that matches certain conditions. We use this to find the last commit to a branch that looks like a release. 
`GitHub#latestTag` now uses this method of finding the last release PR. The previous method looks at the `base` branch of a pull request.
Fixes #740
=> feat: add GitHub#commitsSince and GitHub#findMergeCommit

__snapshots__/github.js, src/github.ts, test/github.ts
Adds a retry parameter to `GitHub#graphqlRequest` which will retry up to that many times on 502 errors.
Fixes #746
=> refactor: graphql retries on 502 errors configurable in GitHub#graphqlRequest()

.eslintrc.json, src/bin/release-please.ts, src/factory.ts, src/github-release.ts, src/index.ts, src/release-pr.ts, src/releasers/go-yoshi.ts, src/releasers/index.ts, src/releasers/java-bom.ts, src/releasers/java-yoshi.ts, src/releasers/node.ts, src/releasers/ocaml.ts, src/releasers/php-yoshi.ts, src/releasers/python.ts, src/releasers/ruby-yoshi.ts, src/releasers/ruby.ts, src/releasers/rust.ts, src/releasers/simple.ts, src/releasers/terraform-module.ts, src/util/branch-name.ts, synth.py, test/cli.ts, test/factory.ts, test/github-release.ts, test/release-pr.ts, test/releasers/index.ts, test/releasers/yoshi-go.ts
releasers/index.js is the source of truth for available releasers. This
change strengthens that by introducing the ReleaseType as the typed
definition of what releasers are available.
Keeping the source of truth (ReleaseType) separate from actual ReleasePR
subclasses allows multiple types to point to the same subclass (e.g. the
case of "go" and "go-yoshi"). Prior to this change it would not have
been possible (via yargs cli options) to specify `--release-type go` (or
at least it's not listed in the help output)
Since the only case for ReleasePR.releaserName is now obviated it's been
removed. If there a need in the future for a "display friendly"
representation of the releaser instance then we can add it back.
=> refactor: stricter releaseType typing

src/commit-split.ts, src/github.ts, test/commit-split.ts, test/helpers.ts, test/releasers/java-bom.ts, test/releasers/java-yoshi.ts, test/releasers/node.ts, test/releasers/utils.ts, test/releasers/yoshi-go.ts
The aggregate releaser will get all commits on the default branch and
use this function to partition them per configured package path to send
to individual releasers.
- packagePaths: restrict splits to specific paths
- includeEmpty: include `git commit --allowEmtpy` commits. Each path gets
a copy.
default behavior is the original: split by 1st child dir, drop empty
commits.
=> refactor: commit-split enhancements

src/github.ts, test/github.ts
The aggregate releaser will want to pass in the sha of a commit to get
the manifest and/or config at the last release commit. Augment
`getFileContentsWithSimpleAPI` to take either a branch name OR a commit
sha to pass as `ref` to `/repos/contents`. Per the docs, `ref` is:
"The name of the commit/branch/tag"
Perhaps they should have named that parameter more generically since
`ref` really [refers only to branch/tag.](https://git-scm.com/book/en/v2/Git-Internals-Git-References)
=> refactor: getFileContentsWithSimpleAPI with commit

__snapshots__/python.js, src/release-pr.ts, src/releasers/node.ts, src/releasers/python.ts, test/releasers/node.ts, test/releasers/python.ts, test/releasers/utils.ts
The aggregate releaser will call into each releaser passing in
relevant commits and the lastest GitHubTag. In return it will receive
the OpenPROptions that releaser would have used to open a PR.
Starting with only Node and Python.
Finally some test coverage for the Python releaser.
=> refactor: releaser interface for aggregate

src/bin/release-please.ts
Not sure if this is something we want to do broadly (add debug helpers). I wrote this for testing the latestTag functionality against real repositories.
=> feat: add latest-tag command which will print out the detected latest tag

src/github.ts
For some reason, a commit can have multiple associated pull requests. We actually want the first result, not the last and this appears to correctly be the associated pull request that we want.
Fixes #756
=> fix: find first associate pull request

.mocharc.js, src/bin/release-please.ts, src/factory.ts, src/github-release.ts, test/cli.ts, test/factory.ts
now that there's an entry point other than `run()` on an instance
(i.e. `ReleasePR.latestTag()`), `runCommand()` needs to be able to
specify what it is. `call()` (formerly `run()`) now accepts this `method`
argument.
Using function overloads as a means to keep a clean call type signature.
=> refactor!: rename factory.run -> call

src/bin/release-please.ts, src/constants.ts, src/factory.ts, src/github.ts, src/index.ts, src/release-pr.ts, src/releasers/index.ts, synth.py, test/factory.ts, test/github.ts
fork is a low level GitHub plumbing configuration. GitHub can make the
decision when it will be able or unable to add/remove labels and close
prs.
BREAKING CHANGE: fork is no longer in ReleasePRConstructorOptions, it is
now in GitHubConstructorOptions.
=> refactor!: move fork down to GitHub

__snapshots__/node.js, src/releasers/python.ts, test/helpers.ts, test/releasers/java-bom.ts, test/releasers/java-yoshi.ts, test/releasers/node.ts, test/releasers/python.ts, test/releasers/utils.ts
- DRY out 1983-10-10 with factored out dateSafe helper
- convert long string asserts in node test to snapshots
- stubFilesToUpdate util enhancements (usage coming in subsequent PRs):
- `flatten`: find fixture files matching repo structure
- `inlineFiles`: stub files from content input instead of file system.
=> refactor: helper/util tweaks to DRY out test code

src/github.ts, src/releasers/java-yoshi.ts, test/releasers/java-yoshi.ts
To build this, we needed to separate the GitHub methods for returning the target branch `getDefaultBranch()` from `getRepositoryDefaultBranch()`.
We should probably rename our usage of `getDefaultBranch()` to `getTargetBranch()`
=> fix: only add the target branch to PR title for non-default branches

src/constants.ts, src/index.ts, src/manifest.ts, src/util/checkpoint.ts, test/manifest.ts
The Manifest class uses a manifest.json file to track version info for
one or more packages* in a repo. The structure is an object of this
shape:
`{"<packagePath>": "<version>"}`
The manifest file must exist at least at the tip of the `defaultBranch`
even if it is empty at first. The Manifest class will attempt to find
the last merged Release PR and use the package versions set in the
manifest at that time as the current versions. Failing to find a package
version it will read the manifest at the tip of the `defaultBranch` to
see if a version has been added. "packagePath" additions are the only
change considered (changed or deleted packagePath entries are ignored).
If a version still cannot be determined then the Manifest falls back to
the individual ReleasePR instance's …
=> refactor(manifest): code layout, file format

__snapshots__/python.js, __snapshots__/version-py.js, src/updaters/python/setup-cfg.ts, src/updaters/python/setup-py.ts, src/updaters/python/version-py.ts, test/updaters/fixtures/version.py
Fixes: https://github.com/googleapis/release-please/issues/777
=> fix: do not change format of Python version files

src/release-pr.ts, test/release-pr.ts
The check for outstanding release PRs would iterate over all PRs on a repo by default.
=> fix(pagination): looking for pending PRs had no pagination limit

__snapshots__/python.js, __snapshots__/ruby.js, src/factory.ts, src/github-release.ts, src/index.ts, src/release-pr.ts, src/releasers/go-yoshi.ts, src/releasers/helm.ts, src/releasers/java-bom.ts, src/releasers/java-yoshi.ts, src/releasers/node.ts, src/releasers/ocaml.ts, src/releasers/php-yoshi.ts, src/releasers/python.ts, src/releasers/ruby.ts, src/releasers/rust.ts, src/releasers/simple.ts, src/releasers/terraform-module.ts, test/cli.ts, test/factory.ts, test/github-release.ts, test/releasers/python.ts, test/releasers/ruby.ts
The releasers already know where their changelog is. It should be
configurable for the `release-pr` command as well.
Also cleaned up test/releasers/python.ts a bit and tested the custom and
default changelogPath settings there.
=> refactor: move changelogPath down to ReleasePR

synth.py
@joeldodge79 added a couple improvements to `.mocharc.js`, such as an `unhandledRejection` handler, which I'm not quite ready to roll out to all our libraries (since I know there are some codebases where we don't want this behavior, e.g., telemetry).
=> build: ignore .mocharc.js

src/commit-split.ts, test/commit-split.ts
All file paths coming back from GitHub GraphQL API calls will have the
`/` separator, no need to handle other platform separators
`root` is unused - remove to avoid the use of path.relative which seems to
normalize any hard-coded `/` separators into path.sep
=> refactor: commit split only needs / sep

src/github.ts, src/updaters/package-json.ts, test/github.ts, test/releasers/node.ts
The node releaser passes contents it retrieves ahead of time for
"package.json" into the PackageJson update to avoid an exra call. This
was not being persisted.
Switched node releaser test to use a mock so we have stricter checks on
how GitHub is being called.
=> fix(node): PackageJson updater sets this.contents

__snapshots__/manifest.js, src/github.ts, src/manifest.ts, src/release-pr.ts, src/releasers/go-yoshi.ts, src/releasers/java-bom.ts, src/releasers/java-yoshi.ts, src/releasers/python.ts, src/releasers/rust.ts, src/releasers/terraform-module.ts, test/manifest.ts
- stronger typing for manifest file: using VersionsMap type
- cleanup logic around manifest handling:
1. retrieving manifest - use overload to distinguish between a call
for the manifest at a specific sha vs at HEAD
2. clearer logic to handle bootstrapping (i.e. falling back to HEAD
manifest and then to defaultInitialVersion)
3. more logging around version determination.
- switch to using a mock in tests
- typo fix in lastMergedPRByHeadBranch graphql query
=> refactor(manifest): manifest handling cleanup

src/commit-split.ts, test/commit-split.ts
discovered this bug that prevented configuring with paths like:
- path/path1
- path/path1-extended
went a little heavy on making it clear to future editors why we're using
hardcoded `/` path separators
=> fix: commit-split paths validation

src/github-release.ts, src/release-pr.ts, test/github-release.ts
Manifest.githubRelease will find the last merged release PR, get each
package's version, and call
GitHubRelease.createRelease(version, mergedPR) for each package.
Also refactored test/github-release.pr to use mocks.
=> refactor(github-release): prep for manifest

src/manifest.ts, test/manifest.ts
While trying to add `"release-as"` and `"boostrap-sha"` config options (PR to come), it became apparent the current method of storing only the `GitHubFileContents` version of the config and manifest made it awkward to refer to those objects again (i.e. having to re-parse the "raw" version)
- `this.headManifest` and `this.configFile` now refer to their parsed data
- moved `readConfig` parsing into `getConfigJson`
=> refactor(manifest): cache parsed json for config and manifest

__snapshots__/manifest.js, src/manifest.ts, test/manifest.ts
Two new manifest config options:
1. bootstrap-sha: optional top-level only
- The first time `manifest-pr` is run against a repo (or setup for
the first time on a new `--default-branch`), it will not find a
previously merged PR as the starting point to collect commits for
determine the next release/changelog. The default behavior is to
iteravily traverse back to the very first commit of the repo. This
option provides an arbitrary place to start. Once at least one release
PR has been merged in the history of the `--default-branch`, this
option is ignored.
2. release-as: optional per package and top-level default
- manually set the next release version for a package. This will not
force a release (there still must be user facing commits since the
last realease). Per-package release-as …
=> refactor(manifest): bootstrap-sha and release-as

src/bin/release-please.ts, src/factory.ts, src/manifest.ts, test/cli.ts, test/commit-split.ts, test/factory.ts
This PR finally connects `Manifest` class commands to the cli:
1. `Manifest.pullRequest()` - `manifest-pr`
2. `Manifest.githubRelease()` - `manifest-release`
the only cli flags available are
a) the base set used for a `GitHub` instance (like `--repo-url`, `--default-branch` etc) and
b) `--config` and `--manifest` to override the respective default locations of `release-please-config.json` and `.release-please-manifest.json`
=> feat(manifest): factory/cli integration

src/github.ts, src/manifest.ts, test/github.ts, test/manifest.ts
commitsSinceShaRest queries the REST API to get files associated directly
with a history of commits. This solves the problem that commitsWithFiles
has with processing a multi-commit PR: it ends up assigning all the
files for the PR to every commit in the PR.
I have not tested it but I think it could replace commitsWithFiles (
but not commitsWithLabels since there are no PRs as part of this query).
=> refactor(github): get files from commits w/out PRs

__snapshots__/manifest.js, docs/manifest-releaser.md, src/manifest.ts, src/release-pr.ts, test/fixtures/manifest/repo/package.json, test/manifest.ts
Add support for a special "." path which indicates that a root module should be released.
This is for the [googleapis use-case](https://github.com/googleapis/google-api-nodejs-client/pull/2559).
CC: @joeldodge79
=> feat(manifest): add support for releasing root module

__snapshots__/java-lts.js, src/releasers/java/version.ts, test/releasers/java/version.ts
The versioning scheme should use `-sp.<number>` instead of `-lts.<number>`
=> fix(java): lts -> sp versioning numbers

__snapshots__/manifest.js, src/commit-split.ts, test/manifest.ts
If "." was anything but the last path in the list, it would result in only receiving changes for the special "." path.
=> fix(manifest): do not group changes under "."

src/index.ts, src/manifest.ts, test/manifest.ts
- `Package` type is really a limited collection of ReleasePROptions and
GitHubReleaseOptions.
- Renamed some internal interfaces used to join package config to
commit/last-version data for ReleasePR instances (`PackageForReleaser`)
and to data for opening a pr (`PackageWithPRData`)
- DRYed out code to instantiate a ReleasePR instance
- reverted `"release-draft"` config option to the original
GitHubReleaseFactoryOptions.draft to remove option parsing complexity:
if we ever need to support a "draft PR" then we'll make sure to
namespace that config option appropriately (e.g. `"draft-pr"`)
=> refactor(manifest): typing cleanup

src/commit-split.ts, test/commit-split.ts
prior to this change commits touching both the following files would be
attributed to the "foo" package:
- foo/bar.ts
- some/sub/dir/foo/another.ts
also moved the '.' package path skipping into the constructor
=> fix(manifest): split commits on exact package path prefix

__snapshots__/cli.js, docs/manifest-releaser.md, src/bin/release-please.ts, src/conventional-commits.ts, src/index.ts, src/manifest.ts, src/release-pr.ts, src/releasers/node.ts, src/releasers/python.ts, test/conventional-commits.ts
opt-in behavior for pre-1.0.0 packages that want to follow the standard
conventional commits behavior of bumping the patch instead of the minor
the motivation for this change is compatibility for node package dependencies with versions < 1.0.0 using [Caret Ranges](https://github.com/npm/node-semver#caret-ranges-123-025-004)
=> feat: allow "standard" pre-1.0.0 patch bumps

src/commit-split.ts, test/commit-split.ts
=> fix(manifest): package paths sharing same prefix being shadowed in commit-split

__snapshots__/java-yoshi.js, package.json, src/index.ts, src/release-pr.ts, src/releasers/java-yoshi.ts, test/releasers/fixtures/java-yoshi/Version.java, test/releasers/java-yoshi.ts
Currently, only Java utilizes this option, but this could be used by
any release strategy.
Towards #305 
Towards #597
=> feat: add ability to specify extra files for releasers to consider

src/release-pr.ts, src/releasers/helm.ts, src/releasers/java-yoshi.ts, src/releasers/node.ts, src/releasers/ocaml.ts, src/releasers/simple.ts, src/releasers/terraform-module.ts
For the basic release PR classes, we should only need to specify the files (updaters) that are necessary. This will greatly ease the process for creating new release types.
=> refactor: move simple-case process into base ReleasePR class

src/release-pr.ts, src/releasers/ruby.ts
Ruby follows the basic workflow, so simplify to only specify the files to update
=> refactor: simplify ruby releaser

__snapshots__/java-lts.js, docs/java-releases.md, package.json, src/releasers/java-lts.ts, src/releasers/java/bump_type.ts, src/releasers/java/version.ts, src/updaters/java/versions-manifest.ts, test/releasers/fixtures/java-yoshi/released-lts-versions.txt, test/releasers/fixtures/java-yoshi/versions-lts-snapshot.txt, test/releasers/java-lts.ts, test/releasers/java/version.ts
The LTS branch will not bump the minor version - it will preserve the
major/minor/patch of the version it was patched from.
=> fix: adjust patch rule for Java LTS strategy

__snapshots__/java-update.js, src/updaters/java/java_update.ts, test/updaters/fixtures/pom-java-lts-snapshot.xml, test/updaters/java-update.ts
=> fix: Java replacer should handle `-sp.1` version replacements

__snapshots__/conventional-commits.js, package.json, src/util/to-conventional-changelog-format.ts, test/conventional-commits.ts
If someone adds a `Release-As` commit, it should be reflected in the CHANGELOG. This has confused a few folks, especially if there have been no user facing commits except `release-as`.
Fixes #749
Refs: https://github.com/conventional-changelog/conventional-changelog/pull/796
=> fix(release-as): commits with Release-As footer now create release

__snapshots__/go.js, src/releasers/go.ts, src/releasers/index.ts, test/releasers/go.ts
Adds a generic golang releaser. It only updates the changlog (defaults to `CHANGES.md`) as tags are the release version.
Fixes #882
=> feat: add generic go releaser

src/releasers/ruby-yoshi.ts, test/releasers/ruby-yoshi.ts
Ruby-Yoshi libraries are currently failing if there is no preexisting release. This is because there is no last package version, and the RubyYoshi releaser is responding by sending a malformed GitHubTag (with undefined name and version) to coerceReleaseCandidate. This PR should fix the releaser so it properly sends undefined as the GitHubTag for this case.
=> fix(ruby-yoshi): Fix the initial release of new Ruby-Yoshi libraries

src/github-release.ts, src/github.ts, src/graphql-to-commits.ts, src/release-pr.ts, src/releasers/go-yoshi.ts, src/releasers/java-yoshi.ts, src/releasers/python.ts, src/releasers/ruby-yoshi.ts, src/releasers/rust.ts, src/updaters/changelog.ts, src/updaters/php-manifest.ts, src/updaters/root-composer.ts
Extraneous error logging is polluting downstream logs (e.g. in the release-please GitHub app logs). This PR converts somewhat important notices to warnings for cases that are not actually errors.
=> fix: convert unnecessary error logs to warnings

src/github.ts, test/fixtures/commits-since-missing-branch.json, test/github.ts
Currently this scenario crashes as the graphQL response contains a null value
Fixes #944
=> fix: finding commits to non-existent branch should return empty array

__snapshots__/node-workspace.js, src/plugins/node-workspace.ts
When running as a GH action, there are times when the plugin does not
set the version correctly on a package. Specifically, if a package is
getting a version bump only because at least one dependency is version
bumping then we see that it only gets a "patch" bump even if there is a
specific releaseAs config key set for that package.
When I try to reproduce this running the cli locally on my mac laptop
the problem disappears.
=> fix: debug logging for node-workspaces plugin

src/errors/index.ts, src/util/release-notes.ts, test/util/release-notes.ts
Throwing a typed error will allow the caller to handle appropriately (file an issue, etc).
Fixes #947
=> fix: throw custom error class for missing release notes error

__snapshots__/manifest.js, docs/manifest-releaser.md, src/manifest.ts, test/manifest.ts
allow specifying an arbitrary sha to represent the last release. This is
helpful to use when trying to revert the last release PR. While you can
revert the changes from a bad release PR and delete associated tags/releases,
GitHub does not allow you to delete the actual PR so release-please will
still find it and consider it the last release.
worked for us in the wild: https://github.com/looker-open-source/sdk-codegen/pull/772
=> feat(manifest): support hard-coded last-release-sha

__snapshots__/python.js, src/release-pr.ts, src/releasers/go.ts, src/releasers/node.ts, src/releasers/python.ts, test/fixtures/latest-tag-python.json, test/release-pr.ts, test/releasers/python.ts
This PR adds partial support for Python's "normal" form pre-release tags, by coercing them into the type of pre-release currently supported by release-please (`-1.0.0b2` becomes `-1.0.0-b2`).
Python now also has the ability to handle pre-releases enabled by default, we likely might want to enable this feature for all languages but thought I'd start with one.
We do not fully support the form `1.0.0b2` for release tags, but using `Release-As:` can still be used.
=> feat(prerelease): support "normal" form for python pre-releases

src/errors/index.ts, src/github.ts, src/releasers/java-yoshi.ts, test/releasers/java-yoshi.ts
Fixes #772 🦕
Have found the cause of the cryptic "Not found" error occurring on private repos. I'm not sure if 403 is actually ever thrown but left it there in case...
=> fix(github-release): private repo not found error

src/releasers/krm-blueprint.ts, src/updaters/krm/krm-blueprint-version.ts
Fixes some issues that came up when testing KRM releaser in manifest mode
- `previousTag` may contain package info if in manifest mode
- only find files in corresponding package path if provided
=> fix: krm releaser manifest mode

.github/workflows/ci.yaml
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
I think it would be interesting to not cancel one job when another fails.
For example, this [job](https://github.com/googleapis/release-please/runs/3285384956?check_suite_focus=true) was cancelled because an installed dependency requires at least Node.js 12.20. It would be interesting to know if the CI will succeed or fail again with a higher version.
EDIT: should it be updated in https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/node_library/.github/workflows/ci.yaml?
=> ci: disable fail-fast

__snapshots__/version-rb.js, src/updaters/version-rb.ts, test/updaters/version-rb.ts
This fixes the linked issue by applying a small fix to `updaters/version-rb.ts`. 
Fixes #1018 🦕
=> feat: handle single quotes in version-rb

__snapshots__/ruby.js, src/releasers/ruby.ts, test/releasers/ruby.ts
Currently, if the `versionFile` option is not provided to the `ruby` releaser, it effectively defaults to `{path}/`, which is never a correct path to a `version.rb` file. Hence, the `versionFile` option is effectively required for the `ruby` releaser. This is a particular problem for the release-please probot app, which does not currently support `versionFile` in its config schema.
This PR provides a valid default equal to the expected path to the `version.rb` file based on Ruby conventions. It works for individual library repos but not monorepos (i.e. it does not prepend a package name subdirectory). This is okay for now because Ruby does not currently have any monorepo cases where this default is needed. And it is consistent with `changelogPath` which behaves the same way.
This also …
=> fix(ruby): The Ruby releaser defaults to the correct version.rb path

__snapshots__/cli.js, src/bin/release-please.ts
The option `--bump-minor-for-patch-pre-major` didn't work. This was because of the typo in the option name, I believe the actual name for the option supposed to be `--bump-patch-for-minor-pre-major`. Changing it makes it work.
Fixes #1049
=> fix: typo in `--bump-patch-for-minor-pre-major` option

__snapshots__/cli.js, src/bin/release-please.ts
The `GitHubReleaseOptions` interface already includes a `releaseLabel` field that controls the label applied to the pull request when `github-release` is run. (When this field is undefined, the logic in `github-release.ts` falls back to `autorelease: tagged`.) If I understand Yargs correctly, this change will allow this field to be set via Yargs.
=> feat: github-release can customize the label applied to the pull request

docs/manifest-releaser.md, src/index.ts, src/manifest.ts, test/manifest.ts
Fixes #1042 🦕
Here is a simple repo that shows the functionality: https://github.com/rabraghib/release-please-tests
=> feat(manifest): add option to skip creating github release

__snapshots__/cli.js, src/bin/release-please.ts, src/factory.ts, src/index.ts, src/release-pr.ts
Allows you to skip the latest tag lookup and specify the previous tag and sha to base the release on.
Example:
```
release-please release-pr --token=$GITHUB_TOKEN \
--repo-url=googleapis/google-cloud-go --package-name=asset \
--path=asset --release-type=go-yoshi --monorepo-tags=true  \
--debug --latest-tag-name=asset/v1.0.0 \
--latest-tag-sha=79837291073d538f8ca768b04afc642bdd25d69b \
--latest-tag-version=1.0.0
```
Creates: https://github.com/googleapis/google-cloud-go/pull/4812
=> feat: allow forcing latest tag

__snapshots__/github.js, src/github.ts, src/manifest.ts, test/github.ts
For merge/rebase/direct commits, the `mergeCommitIterator` was not returning the list of files (no matching pull request found). We now backfill the commits from the REST API.
=> fix: backfill commit files for merge/rebase/direct commits

__snapshots__/cli.js, __snapshots__/github.js, src/bin/release-please.ts, src/github.ts, src/manifest.ts, test/cli.ts, test/github.ts, test/manifest.ts
We introduced the ability to open draft PRs, but it was overloading the `--draft` option. This is now separated into `--draft-pull-request` option.
=> fix: reimplement draft releases

src/manifest.ts, test/cli.ts, test/manifest.ts
fix: return created pull request rather than just the pull request number
This returns the path of the component releases along with the release tag information when building/creating a GitHub release.
=> feat: return path along with created release

__snapshots__/default-changelog-notes.js, src/bin/release-please.ts, src/changelog-notes.ts, src/changelog-notes/default.ts, src/manifest.ts, src/strategies/php-yoshi.ts, src/strategy.ts, test/changelog-notes/default-changelog-notes.ts
ReleaseNotes is renamed to ChangelogNotes and turned into an interface with a default implementation. You can now inject a custom ChangelogNotes implementation to customize the content added to the changelog (and pull request/release notes).
This is in preparation to support adding content to the release notes outside of the changelog contents as well as #1106
=> refactor: rename release-notes to changelog-notes and make it swappable

src/manifest.ts, test/cli.ts
Adds back outputting version, along with `major`/`minor`/`patch`, these outputs are used during GitHub action releases to tag both the version itself, along with a moving `v1`, `v1.2` tag.
=> fix: add back version/major/minor/patch

__snapshots__/cli.js, src/bin/release-please.ts, src/factory.ts, src/manifest.ts, src/strategy.ts, test/cli.ts, test/manifest.ts, test/strategies/base.ts
`--monorepo-tags` option was available to `release-pr` and `github-release` CL commands. It forced adding the component to the release tag (like `component-v1.2.3` vs `v1.2.3`). Manifest commands always set this option by default.
Fixes #1116
=> feat: add `includeComponentInTag` option for strategies and hook up to `--monorepo-tags`

src/manifest.ts, src/strategy.ts, test/manifest.ts
For strategies that fetch a default component (i.e. node reading from `package.json`), it was trying to find a merged PR matching the component. In this case, it failed to find the merged release PR. In the case of Java, which does not detect a default component, it was working because it would fall back to not having a component.
To fix this, we set the component to compare against to the empty string if configured to not `includeComponentInTag`
Fixes #1121
=> fix: Manifest.fromConfig can find latest release version without component

__snapshots__/cli.js, src/bin/release-please.ts, src/factory.ts, src/manifest.ts, src/strategy.ts, test/manifest.ts
Can customize the release pull request title with `pull-request-title-pattern` in the releaser config or via the `--pull-request-title-pattern=<pattern>` in the CLI.
Fixes #1115
=> feat: reimplement custom pull request title

src/util/branch-name.ts, test/manifest.ts, test/util/branch-name.ts
With slashes in the branch name, we can get weird behavior. If a branch already exists named `release-please`, we cannot create any branches that are prefixed with `release-please/` due to git's storage mechanism.
To go along with this, we should re-implement the closing of other release PRs that match component/target branch that do not adhere to the correct branch name.
Fixes #1024 
Fixes #1125
=> fix: switch branch delimiter to `--`

src/manifest.ts, test/manifest.ts
Sometimes, a repository may not have a previous release tagged in the expected format and release-please cannot find it in the history. In those cases, we will use the version specified in the manifest (if there is one) as the previous release.
Fixes #1130
=> fix: backfill latest release with version found in manifest

src/github.ts, test/fixtures/releases.json, test/github.ts
=> fix(github): correctly return maxResults releases

src/manifest.ts, src/plugins/merge.ts, src/util/pull-request-title.ts, test/manifest.ts, test/plugins/merge.ts
Also, skip merging if there is only a single configured package for the manifest.
=> fix: merge manifest release PRs unless separatePullRequests is configured

src/factory.ts, src/strategies/base.ts, src/strategies/dart.ts, src/strategies/elixir.ts, src/strategies/go-yoshi.ts, src/strategies/go.ts, src/strategies/helm.ts, src/strategies/java-yoshi.ts, src/strategies/krm-blueprint.ts, src/strategies/node.ts, src/strategies/ocaml.ts, src/strategies/php-yoshi.ts, src/strategies/php.ts, src/strategies/python.ts, src/strategies/ruby-yoshi.ts, src/strategies/ruby.ts, src/strategies/rust.ts, src/strategies/simple.ts, src/strategies/terraform-module.ts, src/strategy.ts, test/factory.ts, test/strategies/base.ts
This is a cleanup PR to make `Strategy` an interface.
=> refactor: strategy is now an interface and not an abstract class

src/manifest.ts, src/version.ts, test/manifest.ts, test/version.ts
The current method of finding the latest release for non-manifest repositories is to look through latest commits to find a merged PR that looks like a release-please PR for that component. This adds a fallback to consider manually tagged releases if that commit is on the target branch.
Fixes #1132
Towards #1088
=> fix: fallback to look at releases when looking for latest release

owlbot.py
Owlbot shouldn't be overriding the CI scripts in the backport branch.
=> chore: ignore workflow templates in backport branch

__snapshots__/cargo-toml.js, src/updaters/rust/cargo-toml.ts, test/fixtures/strategies/rust/Cargo-crate2.toml, test/fixtures/strategies/rust/Cargo-workspace.toml, test/updaters/cargo-toml.ts, test/updaters/fixtures/Cargo-workspace.toml, test/updaters/fixtures/Cargo.toml
Cherry pick #1095 into v13 and resolve conflicts
Fixes #1094
=> fix(rust): Don't update dev-dependencies lacking a version key (#1095)

src/manifest.ts, test/fixtures/manifest/config/root-release-type.json, test/manifest.ts
We were setting the default too early - if you specified a release-type at the root of the config but left the per-path config empty, the per-path's default would take precedence over the configured root value.
Discovered while investigating #1141
=> fix: allow setting release-type at root of manifest config

__snapshots__/cli.js, docs/cli.md, src/bin/release-please.ts, src/changelog-notes.ts
=> feat: enable specifying changelog section headings in the CLI

src/commit.ts, test/commits.ts
This allows you to retroactively "fix" a merged commit's message by updating the associated merged pull request with a section like:
```
BEGIN_COMMIT_OVERRIDE
feat: add ability to override merged commit message
chore: another message
chore: a third message
END_COMMIT_OVERRIDE
```
Fixes #967
=> feat: add ability to override merged commit message

src/github.ts, src/manifest.ts, test/manifest.ts
Similar to #1146
If we don't find a recent release PR or release, fallback to parsing tags. This should only be necessary for non-manifest releases that are being bootstrapped to release-please.
=> fix: fallback to look at tags when looking for latest release

README.md
=> docs: emphasize multiple commit messages must come at end of message

src/github.ts, src/strategies/krm-blueprint.ts, test/fixtures/pom-file-search-with-prefix.json, test/github.ts, test/strategies/krm-blueprint.ts
This fixes 1164 in the v13 branch, but we will need to backport the fix for 12.x as well
See #1164
=> fix: GitHub#findFilesByExtension should treat prefix as a directory

src/index.ts
This allows other libraries to:
```ts
import {Manifest, ReleaseType} from 'release-please';
```
=> fix: export public interface types from index.ts

__snapshots__/generic.js, docs/customizing.md, src/factory.ts, src/plugins/merge.ts, src/strategies/base.ts, src/strategies/java-yoshi.ts, src/updaters/composite.ts, src/updaters/generic.ts, test/factory.ts, test/strategies/java-yoshi.ts, test/updaters/composite.ts, test/updaters/fixtures/Version.java, test/updaters/generic.ts
This introduces a new `Generic` updater class that scans the file line by line for annotations.
You can annotate a line (inline) via:
* `x-release-please-version`
* `x-release-please-major`
* `x-release-please-minor`
* `x-release-please-patch`
For these annotations, we will try to replace the value on that line only.
You can annotate a block by starting with a line containing:
* `x-release-please-start-version`
* `x-release-please-start-major`
* `x-release-please-start-minor`
* `x-release-please-start-patch`
and close the block with a line containing `x-release-please-end`. Within the block, we will attempt to replace version values.
Additionally, all basic strategies now support the `extra-files` option which will apply this generic updater class.
Fixes #435
Fixes #305
Fixes #1139
Fixes …
=> feat: introduce generic updater

src/plugins/cargo-workspace.ts, src/strategies/rust.ts, src/updaters/rust/cargo-toml.ts, test/strategies/rust.ts, test/updaters/cargo-toml.ts
* Cargo.toml updater now updates the main package version from the updater's version
* cargo-workspace merges the root component's updates
* rust strategy now updates all workspace members versions in sync (overridden by cargo-workspace plugin if configured)
Fixes #1170
Fixes #1096
=> fix(rust): Rust strategy should update root Cargo files in a workspace

__snapshots__/java-update.js, src/strategies/java-yoshi.ts, src/updaters/java/java-update.ts, test/strategies/java-yoshi.ts, test/updaters/fixtures/java-replacements-test.txt, test/updaters/java-update.ts
Updates JavaUpdater to allow only updating `:current` vs `:released` annotated versions.
Fix files updated for snapshot releases (same as normal releases, but skip Changelog).
Fixes #1203
=> fix: java snapshots should update all files with :current annotations

__snapshots__/php-yoshi.js, src/strategies/base.ts, src/strategies/php-yoshi.ts, src/util/pull-request-body.ts, test/fixtures/release-notes/legacy-php-yoshi.txt, test/strategies/php-yoshi.ts, test/util/pull-request-body.ts
PHP Yoshi strategy was creating a manifest-like pull request body with `<summary>` sections however it was not adding the `:` between the component and the version. Moving forward we will make the section include the `:`.
We also adjust the parsing to handle the `<summary>` value without the `:` (which we can possibly remove at a later time). Added a test for parsing the legacy format.
Fixes #1212
=> fix(php-yoshi): fix parsing of pull request body

src/versioning-strategies/default.ts, test/versioning-strategies/default.ts
=> fix: use latest Release-As commit when overriding version

src/util/branch-name.ts, test/util/branch-name.ts
`BranchName.parse` is expected to return `undefined` if a branch name doesn't match one of our expected patterns, not throw exceptions
Fixes #1226
=> fix: BranchName.parse should not throw exceptions

src/util/pull-request-body.ts, test/util/pull-request-body.ts
If you modify the PR body in the GitHub UI, it seems to add windows newlines.
Fixes #1206
=> fix: handle windows newlines in pull request body

src/strategies/python.ts
Somehow missed this in the v13 refactor https://github.com/googleapis/release-please/blob/12.x/src/releasers/python.ts#L35-L48
Fixes https://github.com/googleapis/repo-automation-bots/issues/3111
=> fix(python): restore default changelog config for python

__snapshots__/cargo-workspace.js, __snapshots__/node-workspace.js, __snapshots__/pull-request-body.js, src/manifest.ts, src/plugins/merge.ts, src/util/pull-request-body.ts, test/util/pull-request-body.ts
When merging pull requests for multi-component manifests, always use the component-separate pull request body style.
Fixes #1245
=> fix: multi-component manifest release notes for single component release

src/manifest.ts, src/strategies/base.ts, src/strategies/java-yoshi.ts, src/strategies/php-yoshi.ts, test/manifest.ts
Previously the manifest would just short-circuit and ignore creating pull requests if there are no commits. Now, it's the responsibility of the strategy to decide to skip proposing a pull request or not.
The java-yoshi strategy now forces itself to consider an empty commit set in order to create the -SNAPSHOT pull request
Fixes #1253
=> fix: delegate empty commit handling to strategies

__snapshots__/krm-blueprint-version.js, src/updaters/krm/krm-blueprint-version.ts, test/updaters/krm-blueprint-version.ts
Prior to v13, we were passing around version strings which included `v`. This regex replacement was assuming that the version included `v` which it did not in v13. Also, the tests did not cover the case when a `previousVersion` was provided.
Fixes #1268
=> fix: krm blueprints should update yaml files

src/manifest.ts, test/manifest.ts
It's possible that a manual release was created/tagged since the last release-please PR was merged/released. The logic currently prefers any merged release PR over manually created releases. Now, we stop iterating through commits after we find the first merged release PR, but still consider recent releases (picking the highest number).
Pro: This method is more robust and resilient
Con: We now always iterate over releases with GraphQL queries.
Fixes #1266
=> fix: check recent commits and latest releases for latest version

__snapshots__/github.js, src/factory.ts, src/github.ts, src/manifest.ts, src/strategies/go-yoshi.ts, test/fixtures/commits-since-many-files.json, test/fixtures/manifest/config/include-component-in-tag.json, test/fixtures/manifest/config/tag-separator.json, test/github.ts, test/manifest.ts
fix: allow configuring includeComponentInTag and tagSeparator from manifest config
fix(go-yoshi): should not always skip modules
fix: correctly fetch full list of files
fix: Manifest should be able to find tagged versions without a release
=> fix(go-yoshi): allows using go-yoshi with manifest

src/strategies/base.ts, test/manifest.ts
If you have a component-less configuration, it should not try to handle a release for a standalone release PR that does have a component (it will incorrectly attempt to tag the release)
This check ensure that we only have the configured component releaser attempting to tag the release.
=> fix: standalone releases should only be released by its matching component

__snapshots__/cli.js, src/bin/release-please.ts, src/manifest.ts, src/strategies/base.ts, src/util/tag-name.ts, test/fixtures/manifest/config/include-v-in-tag.json, test/manifest.ts, test/strategies/base.ts, test/util/tag-name.ts
Adds new configuration option `includeVInTag` or `include-v-in-tag` in the manifest JSON.
Fixes #1103
=> feat: allow configuring tag without "v"

src/github.ts, test/github.ts
release-please now returns an addition `uploadUrl` field when creating a release. Additionally, we fix it to look in all the body fields (`body_text`, `body`, and `body_html`) to attempt to return the release notes. This value has been returned as `notes` since v13 and will continue to do so.
Fixes #1286
=> fix: return uploadUrl and body when creating release

src/strategies/go-yoshi.ts, test/strategies/go-yoshi.ts
The root module was always intended to only include non-submodule components. We now dynamically load the list by finding the `go.mod` files in the repository.
This fixes the root component release PRs to look like: https://github.com/googleapis/google-cloud-go/pull/5498
=> fix(go-yoshi): dynamically load list of ignored submodules for google-cloud-go

__snapshots__/manifest.js, __snapshots__/pull-request-body.js, src/util/pull-request-body.ts, test/fixtures/release-notes/mixed-componentless-manifest.txt, test/manifest.ts, test/util/pull-request-body.ts
We now build a more friendly `<summary>` section with just the version. `PullRequestBody` can create and parse this new format.
Fixes #1294
=> fix: manifest release can handle componentless entry

src/github.ts, test/github.ts
#1280 started throwing `FileNotFoundError` for missing files. When we build the changeset, we should catch this error rather than trying to catch the underlying GitHub API error.
=> fix: catch FileNotFound error when building changeset

src/util/branch-name.ts, test/util/branch-name.ts
Autorelease branch naming can mistakenly match for any branch
beginning with a v.  A PR branch like
"release-please--branches--v3.3.x" will be treated as an autorelease
branch for a component called "please--branches-".
If the branch name is a valid semver, the wrong class will be chosen
to parse the branch name, and later steps will fail.  If it's not a
valid semver, then branch parsing will completely fail.
This excludes these false-positive matches by excluding branches which
start with "release-please--branches".
Fixes #1310 🦕
=> fix: address false-positive matches for autorelease branch naming

src/manifest.ts, test/manifest.ts
Catch duplicate release errors when handling a manifest release. If all releases fail because of duplicate release errors, then it should throw the duplicate release error.
Fixes #1313
=> fix: handle failures during multiple release creation

__snapshots__/node-workspace.js, src/plugins/node-workspace.ts, test/plugins/node-workspace.ts
We are correctly calculating the final version numbers in the node-workspace plugin, but we aren't setting the version entry in the package.json (we were correctly updating the versions in the dependencies sections).
Fixes #1317
=> fix: node-workspace plugin should update package.json versions

src/bin/release-please.ts, src/manifest.ts
=> fix: tagging many GitHub releases should not require a file touched check

__snapshots__/generic-xml.js, docs/customizing.md, package.json, src/manifest.ts, src/strategies/base.ts, src/updaters/generic-xml.ts, test/strategies/base.ts, test/updaters/generic-xml.ts
For most release strategies, you can provide additional files to update
using the [GenericXml](/src/updaters/generic-xml.ts) updater. You can
specify a configuration object in the `extra-files` option in the manifest
configuration.
```json
{
"extra-files": [
{
"type": "xml",
"path": "path/to/file.xml",
"xpath": "//xpath/to/field"
}
]
}
```
=> feat: introduce generic xml updater

src/changelog-notes.ts, src/strategies/base.ts, src/strategies/go-yoshi.ts
Related to #1331 and #1341, this improves extendibility of the tool. 
Sometimes changelog generator might use raw commits as a source (as actually does `GitHubChangelogNotes` in a way), or combination of both.
=> refactor: pass raw commit log to ChangelogNotes.buildNotes

__snapshots__/ruby-yoshi.js, src/strategies/ruby-yoshi.ts, test/strategies/ruby-yoshi.ts
Currently Ruby repos are pinned to release-please 12.x for several reasons, among them being that the release-please 13 rewrite reverted Ruby's preferred changelog formatting. This PR updates the `ruby-yoshi` strategy to reimplement this formatting as a postprocessing pass to buildReleaseNotes. Specifically:
* It standardizes on h3 for all version headers, regardless of whether it's a major/minor or patch version.
* It removes the diff link on version headers, as we prefer not to have links in the changelog.
* If a commit message includes a pull request number, conventional commits turns it into a link. We remove that link.
* We collapse vertical whitespace of two or more blank lines.
This PR also removes the custom pull request body logic in `yoshi-ruby`. We were not using that …
=> fix: Restore v12 changelog formatting for ruby-yoshi

.github/workflows/ci.yaml
Looks like one of the dependencies doesn't like node 15. (See #1363, a no-op change that is failing CI on node 15.)
=> chore: update ci to test node 16 rather than node 15

.bots/header-checker-lint.json
The header-checker-lint bot uses a .github yaml file instead of this custom json file
=> chore: remove unused legacy config

.github/workflows/ci.yaml, src/bin/release-please.ts, src/manifest.ts, test/cli.ts, test/manifest.ts
I would like to honor the `--path` and `--release-as` flags when running `release-pr` with a manifest. These command-line flags already exist and are used in the non-manifest case but are currently ignored in the manifest case.
* `--path` would cause only the specified path to be run from the manifest, and would skip all others.
* `--release-as` would set the `releaseAs` option for _all_ packages to be released (and would override any settings in the config file). Typically it would be used in conjunction with `--path`.
I want these for google-cloud-ruby because:
* I'd rather have a single manifest listing all ~300 packages instead of separate manifests for each package (since the latter would require ~300 executions of release-please and massively inefficient especially in terms of …
=> feat: support selecting a single path when releasing from a manifest

src/github.ts
If the results exceed maxResults, the iteration doesn't stop immediately. It keeps making requests until the data runs out (or we run into quota/throttling issues) because the existing break (lines 648 and 737) break out of the inner loop, not the outer loop.
=> fix: fixed maxResults check in tag and release iterators

src/github.ts
Fixes #1376
chore: add trace logging for when we hit 502s from the GraphQL API
fix: don't crash when pull request iterator GraphQL returns no response
fix: GraphQL retry now uses exponential backoff
=> fix: bump retries for pull request iterator from 1 to 3

src/strategies/base.ts, src/strategies/java.ts, test/strategies/java-yoshi.ts
Files were not being updated because the `versionsMap` was not version bumping the component versions
Fixes #1381
=> fix(java): snapshots should bump versionsMap versions

package.json, src/bin/release-please.ts, src/github.ts
This will aid in debugging release-pr creation
Note that `diff` `^5.0.0` is what's used by the underlying `code-suggester` library as well.
Example usage:
```
release-please release-pr \
--token=${GITHUB_TOKEN} \
--repo-url=googleapis/java-bigquery \
--release-type=java-yoshi \
--trace \
--dry-run
```
=> feat(cli): show file diff for release-pr command with --dry-run and --trace

__snapshots__/cli.js, src/factories/changelog-notes-factory.ts, src/factories/plugin-factory.ts, src/factories/versioning-strategy-factory.ts, src/factory.ts, src/index.ts, src/manifest.ts, src/strategies/base.ts, src/strategies/java.ts, src/strategies/ruby-yoshi.ts, src/strategies/ruby.ts, src/strategies/simple.ts, test/factories/changelog-notes-factory.ts, test/factories/plugin-factory.ts, test/factories/versioning-strategy-factory.ts, test/factory.ts, test/manifest.ts
Extend current code by registering new plugin/strategy before invoking release-please. This makes possible to extend this tool by composition, instead of inheritance (forking).
Closes #1341
=> feat: extensible factories

package.json, src/updaters/base-xml.ts
xmldom could no longer be published, so the maintainers switched to a
namespaced package name.
=> fix(deps): switch from `xmldom` to `@xmldom/xmldom` and update to v0.8.2

src/bin/release-please.ts, test/cli.ts
I want to be able to pass `--label=` (i.e. an empty value) to prevent release-please from attempting to add any labels. Currently this doesn't work because javascript thinks `""` is falsy, and the labels still default to `autorelease: pending`.
=> fix: Allow an empty value for --label

docs/manifest-releaser.md, src/manifest.ts, test/fixtures/manifest/config/search-depth.json, test/helpers.ts, test/manifest.ts
=> feat: allow configuring `release-search-depth` and `commit-search-depth`

__snapshots__/cli.js, docs/cli.md, src/bin/release-please.ts, src/github.ts, src/manifest.ts, test/cli.ts
Introduces the flag `--skip-labeling` that skips the application of labels to newly created pull requests (even if the `label` option is set). We keep the label option set (e.g. to its default of `['autorelease: pending']`) throughout the manifest logic so that it does not affect that logic or plugin logic, but then when it gets into the `github.ts` layer we use the new flag to disable the additional API call that sets the labels after the pull request is created.
This is needed for use cases that call the release-please CLI using a token (such as `YOSHI_CODE_BOT_TOKEN`) that does not have permissions on the repo. In such cases, the second call that sets labels on the newly created PR will fail from insufficient permissions, thus causing release-please to terminate with an error. Repos …
=> feat: add a flag to disable adding labels to new pull requests

docs/cli.md, docs/manifest-releaser.md, src/manifest.ts
When running release-please on the google-cloud-ruby manifest, we're running afoul of secondary rate limits. Currently release-please runs pull request creation concurrently, and in this case, it was trying to open 33 pull requests at once which seemed to be too much. So we're introducing an option to run them sequentially using blocking calls.
This was added to the manifest config rather than the CLI options, because it seems to be a scaling-related knob that should be set per repository, rather than something that depends on how release-please is invoked.
I honestly do not know how to write a test for this. I tested manually both the sequential and concurrent cases to make sure the functionality was still correct, but I'm not sure how to test whether something happened concurrently or …
=> feat: Support sequential-calls manifest field that disables concurrency when creating multiple pull requests or releases

__snapshots__/cargo-workspace.js, src/plugins/cargo-workspace.ts, src/plugins/workspace.ts, test/plugins/cargo-workspace.ts
It's unclear why we always bump cargo versions for untouched components.
Fixes #1407
=> fix(cargo-workspace): stop defaulting to updating all components

__snapshots__/node-workspace.js, src/plugins/node-workspace.ts, test/fixtures/plugins/node-workspace/plugin1/package.json, test/plugins/node-workspace.ts
=> fix: node-workspace should not bump versions for peer dependencies

src/manifest.ts, src/plugins/merge.ts, src/strategies/base.ts, test/manifest.ts
Allows configuring `separate-pull-requests` for individual components. They will be excluded from any merged pull request.
Fixes #1411
=> feat: allow configuring separate-pull-requests per component

src/strategies/base.ts, test/manifest.ts
Fixes #1424 
When tagging a single component, correctly use the branch component for finding appropriate release notes.
=> fix: release tagging can find branch components

src/manifest.ts, test/manifest.ts
release-please is currently not able to recover from quota issues on very large release manifest PRs.
After this PR, release-please will set the correct releases labels on the PR if it created all the releases or found duplicate tags for the non-created ones.
Towards https://github.com/googleapis/repo-automation-bots/issues/3428
=> fix: add release labels if release PR was completed

src/util/commit-split.ts, test/util/commit-split.ts
When using `CommitSplit` with `includeEmpty` and `packagePaths`, include empty commits in all `packagePaths`, not just the ones that already have commits to them.
Fixes #1360
=> fix: CommitSplit with includeEmpty should add commit to all packages

src/manifest.ts, src/strategies/base.ts, src/strategy.ts, test/manifest.ts
Pull request branch name should check the branch component. This causes some release PRs to be missed.
=> fix: Manifest.fromConfig should find branch component

src/manifest.ts, test/manifest.ts
`Manifest.fromConfig` is failing to match releases when `includeComponentInTag: false` and the release has a component.
Towards https://github.com/googleapis/repo-automation-bots/issues/3730
=> fix: all release tag matching if includeComponentInTag is false

__snapshots__/generic-yaml.js, src/manifest.ts, src/strategies/base.ts, src/updaters/generic-yaml.ts, test/strategies/base.ts, test/updaters/fixtures/yaml/invalid.txt, test/updaters/fixtures/yaml/multi.yaml, test/updaters/generic-yaml.ts
This complements `GenericJson` updater.
Note that used parser does reformat the document and removes all comments,
and converts everything to pure YAML (even JSON source). It is same behavior is `ChartYaml` updater has.
If you want to retain formatting, use generic updater with comment hints.
When applied on multi-document file, it updates all documents.
=> feat(yaml): add support for yaml updater

src/util/tag-name.ts, test/util/tag-name.ts
First of all: Sorry I did not create an issue first, but the change is luckily not that big. I'm happy to change.
The underlying issue appeared in our [logs ](https://github.com/netlify/cli/runs/6599918199?check_suite_focus=true) with:
```
⚠ Found release tag with component 'v', but not configured in manifest
```
The problem started with this PR: #1346. This PR changed the tag parsing and made the `v` optional. This works for versions like `v1.1.1`, but as soon as the major version is above 9 like `v10.1.1` it will detect `v` as the component, `1` as the separator and `0.1.1` as the version.
The fix is simply to ensure the separator is not a number, which I believe is a reasonable assumption. :)
I'm a little bit confused why it is working for this repository, as you also have already …
=> fix: Fix parsing of tags with major versions higher than 9

docs/customizing.md
I noticed one of the links in the documentation was broken, so I fixed it:
=> docs: Correct broken link

src/factories/changelog-notes-factory.ts, src/factories/plugin-factory.ts, src/factories/versioning-strategy-factory.ts, src/factory.ts, test/factories/versioning-strategy-factory.ts
If a repository has configured an invalid type, we now throw a ConfigurationError instead of a generic Error to allow integrations to handle this condition more easily.
Towards https://github.com/googleapis/repo-automation-bots/issues/3870
=> fix: factory errors for unknown types throw ConfigurationError instead of Error

src/manifest.ts, test/manifest.ts
This allows integrations to catch this case and log an error on the repository.
Towards https://github.com/googleapis/repo-automation-bots/issues/3867
=> fix: handle malformed manifest JSON and throw ConfigurationError

src/strategies/go-yoshi.ts
google-cloud-go releases may contain a "Miscellaneous Chores" section in the changelog, which is not desired ([example](https://github.com/googleapis/google-cloud-go/releases/tag/talent%2Fv0.8.0)).
=> fix(go): hide unwanted changelog sections

.github/workflows/ci.yaml, package.json
There appears to be a regression in [6.37.1](https://github.com/octokit/types.ts/releases/tag/v6.37.1).
This is to unblock PRs. `@octokit/types` is a dev dependency.
=> deps: temporarily pin `@octokit/types` to 6.37.0

docs/cli.md
Some time ago the option `--include-v-in-tags` was added in <https://github.com/googleapis/release-please/pull/1346>. As of today this has not been documented in the document for the CLI yet. This PR adds the two missing lines.
Note that there are probably other places where documentation of this new option is still missing.
=> docs: add missing option --include-v-in-tags to cli docs

src/util/pull-request-title.ts, test/util/pull-request-title.ts
=> fix: pull request title component can include '/'

src/manifest.ts, test/fixtures/manifest/config/changelog-type.json, test/manifest.ts
=> fix: correctly parse the changelog-type from the manifest config

README.md
Refs #1507 🦕
- - - - 
The Contributing README section about synthtool templating/manatement is not true.
- Readme is not managed
- There are no samples (broken link)
- .nycrc is not managed
- tsconfig is probably not explicitly excluded, but observing history shows it's being worked on here locally…
- The template link is broken (and unnecessary)
=> docs(readme): remove synthtool warning

README.md
Adds a trivial missing word in lifecycle information in Readme.
Along the way a few missing prepositions or whitespace fixed, along with product name Upper Case occurrences in need of fixing.
=> docs(readme): fix wording, spacing, case

.github/generated-files-bot.yml, owlbot.py
Stops extra warnings for files that aren't actually managed by owlbot
Fixes #1507
=> chore: remove generated-files-bot warnings for README.md

src/strategies/base.ts, test/fixtures/release-notes/grouped.txt, test/manifest.ts
When a multi-component release PR was merged, we were rejecting untouched components only because we didn't find a version. However, if the group pull request title pattern was overridden and provided a version, we would not reject the release.
Now, we reject components if we do not find release data for them in the pull request.
Fixes #1527 
Fixes #1536
=> fix: skip component when manifest release does not include component

__snapshots__/bootstrapper.js, src/manifest.ts, src/updaters/release-please-config.ts, test/bootstrapper.ts
We were directly writing the ReleaserConfig to the `release-please-config.json`, but the keys are actually dasherized.
Fixes #1522
=> fix: convert ReleaserConfig JSON keys when bootstrapping

README.md, docs/design.md
Adds a brain dump of the implementation design of this library and a few pointers for contributing.
This doc is aimed at maintainers of this libraries and folks who wish to contribute to this project. It is not written for developers who want to use release-please.
=> docs: add design page/contributor guide

__snapshots__/cargo-workspace.js, __snapshots__/linked-versions-workspace.js, __snapshots__/linked-versions.js, docs/manifest-releaser.md, schemas/config.json, src/factories/plugin-factory.ts, src/manifest.ts, src/plugins/cargo-workspace.ts, src/plugins/linked-versions.ts, src/plugins/workspace.ts, test/plugins/cargo-workspace.ts, test/plugins/compatibility/linked-versions-workspace.ts, test/plugins/linked-versions.ts
By default, plugins that act across multiple candidate releases merge them together because they should be released together. This feature allows configuring the plugins so that they can skip this merge. This allows further plugins to see each modified candidate release.
Fixes #1457
=> feat: allow plugins to skip merging in-scope pull requests

__snapshots__/php-composer-update-packages.js
Running `npm test` removes these extraneous snapshot entries
=> chore: remove extraneous snapshot entries

src/github.ts, src/manifest.ts, test/manifest.ts
Occasionally, GitHub's GraphQL endpoint throws 502s when it takes too long to execute a query. We usually silently retry these requests (with exponential backoff). Previously, if too many attempts are made, we return an empty response. We introduce a new `requireResponse` option which will tell our GraphQL executor to throw the underlying API error if a response is required.
Fixes #1567
=> fix: throw underlying API error when the manifest fetch commits when determining the latest released version

schemas/config.json
Did some additional testing on #1584 and noticed a couple issues:
1) `$schema` needed to be added to the properties array for it to be picked up
2) If you want to reference the schema via a relative (local) path, you need to use uri-reference instead of uri
=> fix: Allow $schema key in manifest config schema

src/github.ts, test/github.ts
Unreleased #1585 started using the extracted `RepositoryFileCache` from `git-file-utils`. As part of the extraction, a separate `MissingFileError` was introduced and is thrown from the cache. To preserve the interface of our `GitHub` class, we need to catch this new error and throw our own.
=> fix: convert `MissingFileError` thrown by `git-file-utils`

package.json, src/github.ts
Towards https://github.com/googleapis/repo-automation-bots/issues/4157
fix(deps): update git-file-utils to 1.1.0
=> fix: use git-file-utils' cache for file search

src/github.ts
We added support for a custom logger instance in the GitHub API wrapper, but the constructor is private. This adds the option as a `GitHub.create` option.
=> fix: allow providing logger to GitHub.create

__snapshots__/node-workspace.js, src/plugins/node-workspace.ts, test/fixtures/plugins/node-workspace/package.json, test/plugins/node-workspace.ts
Here is a simple fix for #1605. All it does is remove the `candidate.path !== ROOT_PROJECT_PATH` check so the root package is considered `inScope` when collecting candidate pull requests with the `node-workspace` plugin.
Like I mentioned in the issue, I'm not sure if this is the correct approach. I did notice that both the maven and cargo plugins do not have this check, so that led me to believe that it might be.
I only have knowledge of the npm ecosystem, where I've seen both monorepos where the root is only used for configuration and where the root is a publishable package.
My assumption here, without a deep knowledge of the codebase, is that if the root package is included in the manifest via the `'.'` key, it should always be considered in scope when generating candidate PRs.
Fixes …
=> fix: dont filter out root package in node workspace candidate filtering

__snapshots__/changelog.js, src/updaters/changelog.ts, test/updaters/changelog.ts, test/updaters/fixtures/CHANGELOG-non-conforming.md
Rather than overwriting the existing release notes that do not conform to the expected release-please format, prepend the new changelog entry. Also, downgrade any existing H1s to H2s.
This will help us on-board new repositories with existing changelogs that do not match our style.
Fixes #1478
=> fix: prepend release notes to non-conforming changelog

docs/manifest-releaser.md, schemas/config.json, src/factories/plugin-factory.ts, src/manifest.ts, src/plugin.ts, src/plugins/sentence-case.ts, test/manifest.ts, test/plugins/sentence-case.ts
Introduces processCommits hook for WorkspacePlugins, and implements the
SentenceCase plugin, which can be used to uppercase the first word
in a commit messages' description.
CC: @martinvarelaj
=> feat(plugins): introduce processCommits hook for plugins

src/plugins/sentence-case.ts, test/plugins/sentence-case.ts
Address bug with sentence case plugin when a commit has multiple `:` characters.
=> fix(sentence-case): handle multiple : in subject

package.json, schemas/config.json, src/github.ts, src/manifest.ts, src/strategies/base.ts, src/strategies/java.ts, test/fixtures/manifest/config/extra-files-glob.json, test/strategies/base.ts
When specifying `extra-files` in a manifest, you can add a `glob: true` entry and the `path` specified will be treated as a file glob.
Fixes #1619
=> feat: allow specifying glob option for extra-files

src/util/commit-split.ts, test/util/commit-split.ts
Previously two prefixes were considered overlapping if one was contained in the other. For example `/config/` and `/aws/config/` would fail even though the prefix is unique.
Fixes: #1637
Fixes #1637
=> fix: detect overlaping prefixes

__snapshots__/default-changelog-notes.js, src/changelog-notes/default.ts, test/changelog-notes/default-changelog-notes.ts
The output of the `ChangelogNotes` interface is expected to be markdown content. We'll escape open/close angle brackets when we generate the notes.
Fixes #1659
=> fix: escape html tags in release notes

docs/manifest-releaser.md, schemas/config.json, src/factories/plugin-factory.ts, src/manifest.ts, src/plugins/group-priority.ts, src/release-pull-request.ts, src/strategies/base.ts, src/strategies/java.ts, test/factories/plugin-factory.ts, test/fixtures/manifest/config/group-priority.json, test/helpers.ts, test/plugins/cargo-workspace.ts, test/plugins/group-priority.ts, test/plugins/maven-workspace.ts, test/plugins/merge.ts, test/plugins/node-workspace.ts
This plugin allows you to configure pull request by priority. If enabled and if a pull request of a prioritized group is found, release-please will limit the proposed release pull requests to the prioritized group only.
For example, java snapshot PRs are now marked as part of the `snapshot` group. If you configure the `group-priority` plugin with the group set to `['snapshot']`, then release-please will only open pull requests for `snapshot` pull requests if there are any.
Fixes #1657
=> feat: add `group-priority` plugin

schemas/config.json, src/manifest.ts, src/strategies/base.ts, src/strategies/java.ts, src/strategies/php-yoshi.ts, test/fixtures/manifest/config/extra-labels.json, test/manifest.ts, test/strategies/base.ts
We are adding a new `extra-label` option which is non-load bearing (we use the existing `label` and `release-label` to indentify which PRs are release-please's and what state they are in).
This new option allows maintainers to organize their components (e.g. labeling with and API component label or perhaps a language)
Fixes #1624
BEGIN_NESTED_COMMIT
fix: fix schema definition for label and release-label
These fields are not actually configurable per-component.
END_NESTED_COMMIT
=> feat: add ability to set extra labels on components

src/bin/release-please.ts, src/bootstrapper.ts, src/updaters/release-please-manifest.ts
Add the `$schema` field to the bootstrapped manifest config file. This helps IDEs automatically lint the config schema as it's being edited.
Fixes the `--dry-run` argument for the bootstrap command to output what it would propose as a change
Fixes #1625
Fixes #1617
fix(cli): bootstrap command respects --dry-run argument
=> fix: manifest config bootstrapper should include schema field

src/bin/release-please.ts, src/manifest.ts, src/plugins/linked-versions.ts, test/manifest.ts
This will be useful for debugging manifest config files.
Example usage:
```bash
release-please debug-config \
--token=${GITHUB_TOKEN} \
--repo-url=googleapis/google-cloud-go \
--config-file=release-please-config-yoshi-submodules.json \
--manifest-file=.release-please-manifest-submodules.json \
--debug
```
It will load the config and the latest versions and print the parsed configs to stdout.
=> feat(cli): add debug command for loading a manifest config

__snapshots__/maven-workspace.js, src/plugins/maven-workspace.ts, test/plugins/maven-workspace.ts
When updating dependencies on a `pom.xml` in `maven-workspace` plugin, preserve the original `pom.xml` update -- do not assume it is a plain `PomXml` updater that can be overwritten.
Fixes #1676
=> fix(maven-workspace): preserve original pom.xml updater when bumping dependencies

__snapshots__/maven-workspace.js, docs/manifest-releaser.md, package.json, schemas/config.json, src/factories/plugin-factory.ts, src/manifest.ts, src/plugins/maven-workspace.ts, src/plugins/workspace.ts, src/util/logger.ts, test/factories/plugin-factory.ts, test/fixtures/manifest/config/maven-workspace-plugins.json, test/fixtures/plugins/maven-workspace/bom/pom.xml, test/fixtures/plugins/maven-workspace/multi1/bom/pom.xml, test/fixtures/plugins/maven-workspace/multi1/pom.xml, test/fixtures/plugins/maven-workspace/multi1/primary/pom.xml, test/fixtures/plugins/maven-workspace/multi1/sub1/pom.xml, test/fixtures/plugins/maven-workspace/multi1/sub2/pom.xml, test/fixtures/plugins/maven-workspace/multi2/bom/pom.xml, test/fixtures/plugins/maven-workspace/multi2/pom.xml, test/fixtures/plugins/maven-workspace/multi2/primary/pom.xml, test/fixtures/plugins/maven-workspace/multi2/sub1/pom.xml, test/fixtures/plugins/maven-workspace/multi2/sub2/pom.xml, test/manifest.ts, test/plugins/maven-workspace.ts
Maven projects can have multiple artifacts within each component. When using the `maven-workspace` plugin, we would like to be able to version bump any of the artifacts in a released component.
Consider a repository with 3 components:
1. `bom`
2. `lib1`
3. `lib2`
The `bom` project is a bill of materials project that references the versions from libraries contained in `lib1` and `lib2`.
| pom file | artifact name | depends on |
| --- | --- | --- |
| bom/pom.xml | com.google.example:my-bom | com.google.example:lib1-bom, com.google.example:lib2-bom |
| lib1/pom.xml | com.google.example:lib1-parent | |
| lib1/bom/pom.xml | com.google.example:lib1-bom | |
| lib1/artifact1/pom.xml | com.google.example:lib1-artifact1 | |
| lib2/pom.xml | com.google.example:lib2-parent | |
| lib2/bom/pom.xml | …
=> feat(maven-workspace): update all discovered pom.xml within the components

src/github.ts, test/github.ts
Do not rely on the default sort order which can change
Fixes #1684
=> fix: explicitly sort PRs by updated desc

__snapshots__/github.js, __snapshots__/pull-request-overflow-handler.js, src/github.ts, src/manifest.ts, src/util/pull-request-body.ts, src/util/pull-request-overflow-handler.ts, test/fixtures/release-notes/overflow.txt, test/github.ts, test/manifest.ts, test/util/pull-request-overflow-handler.ts
When release notes are too big to fit into the pull request body, we must store the release notes somewhere. We implement a `PullRequestOverflowHandler` interface that writes the full changes to a new file in a new branch. The release PR includes a link to the file so that the GitHub UI can render it nicely for us.
When release-please parses the merged release pull request, if it detects the overflow case, we download the release notes from that stored file and use it to determine which releases to tag.
Fixes #1675
=> feat: handle extremely large pull request body fields

src/github.ts, src/manifest.ts, test/github.ts, test/helpers.ts, test/manifest.ts
Currently, the pull request body overflow handler is running for new pull requests, but not on updated pull requests
=> fix: updating a pull request uses overflow handler if body is too large

src/plugins/maven-workspace.ts, src/plugins/workspace.ts, test/plugins/maven-workspace.ts
Fixes #1718
Example new PR: https://github.com/googleapis/google-cloud-java/pull/8699
=> fix(maven-workspace): SNAPSHOT versions should not be included in the manifest

__snapshots__/cargo-workspace.js, src/plugins/cargo-workspace.ts, test/fixtures/plugins/cargo-workspace/Cargo.toml, test/fixtures/plugins/cargo-workspace/packages/rustE/Cargo.toml, test/plugins/cargo-workspace.ts
Hello, I wrote a fix while tracking down #1729 
I'm happy to discuss an alternative approach, but since I already wrote this fix I figured I would put it up for consideration.
TL;DR of the issue is that a Cargo manifest can have compilation target-scoped dependencies, and these must be taken into consideration in addition to the top-level set of dependencies.
Fixes #1729 :crab:
=> fix(cargo-workspace): Update target dependencies in Cargo workspace packages

__snapshots__/node-workspace.js, src/plugins/node-workspace.ts, test/plugins/node-workspace.ts
=> feat(node-workspace): maintain current version range prefix

CONTRIBUTING.md
Hi team, just adding some stuff to the guide that maybe useful for contributors.
@suztomo Opened this new PR because I was unable to edit the last one, looks like I messed up with the head of that branch while working on the versioning strategy. Also, there are no steps to generate release-please command afaik. It is included in the node build command. Multi-line command is fixed.
@chingor13 can you please approve this one?
=> chore: Adding local testing steps to contributing guide

__snapshots__/node-workspace.js, src/plugins/node-workspace.ts
In https://github.com/googleapis/release-please/pull/1723 I overlooked that prefix is also generated in the newCandidate as I incorrectly assumed that that method is only invoked for new packages. It's actually invoked for new updated of any package.
Fixes #1723 🦕
=> fix(node-workspace): maintain the dependency version prefix in newCandidate

README.md, docs/troubleshooting.md
=> docs: add troubleshooting page

__snapshots__/default-changelog-notes.js, src/changelog-notes/default.ts, test/changelog-notes/default-changelog-notes.ts
This is somewhat hacky as we are delegating the changelog generation to the conventional-changelog-writer package which is not doing the explicit issue linking for `notes`. That library has not been updated in months so it's unlikely that we can fix it there.
In the future, we should consider bringing the changelog generation in-house into the `DefaultChangelogNotes` class.
Fixes #1754
=> fix: handle issue links in BREAKING_CHANGE notes section

__snapshots__/version-rb.js, src/updaters/ruby/version-rb.ts, test/updaters/fixtures/version-with-long-patch.rb, test/updaters/version-rb.ts
This fixes the linked issue by applying a small fix to updaters/version-rb.ts.
Fixes #1761 🦕
=> fix: handle incrementing ruby patch versions larger than 1 digit

__snapshots__/linked-versions-group-title.js, src/manifest.ts, src/plugins/linked-versions.ts, src/strategies/base.ts, src/strategy.ts, test/helpers.ts, test/plugins/compatibility/linked-versions-group-title.ts
If you configure a `group-pull-request-title-pattern`, the strategies are rejecting the pull request because they do not know about the custom format. Now we provide the configured value so that strategies can parse the releases.
Fixes #1456
=> fix: pass group-pull-request-title-pattern to strategies to parse releases

__snapshots__/app-json.js, src/updaters/expo/app-json.ts
=> fix: android version now correctly builds as a number

src/manifest.ts, src/strategies/base.ts, src/strategy.ts
This will give strategies an option to create multiple tags from a single PR. For example, `java-yoshi` for a monorepo could configure itself to be a single component (create a single release PR), but then create several releases/tags.
=> feat!: strategies can parse multiple releases from single release PR

__snapshots__/gemfile-lock.js, __snapshots__/version-rb.js, src/strategies/ruby.ts, src/updaters/ruby/common.ts, src/updaters/ruby/gemfile-lock.ts, src/updaters/ruby/version-rb.ts, test/strategies/ruby.ts, test/updaters/fixtures/Gemfile.lock, test/updaters/fixtures/version-with-prerelease.rb, test/updaters/gemfile-lock.ts, test/updaters/ruby/common.ts, test/updaters/version-rb.ts
Fixes #1768 🦕
Adds support for updating the ruby gem version in a committed Gemfile.lock file. This helps ensure that bundle install works correctly after a version.rb version change. There is also some additional logic introduced to simulate how ruby Gem::Version handles `-` with prerelease semvers (e.g. `1.0.0-alpha` is parsed as `1.0.0.pre.alpha).
A future update could make use of the new common stringifyRubyVersion to translate the version into the more commonly used `.` prerelease seperatorwhich is treated "as is" and avoids the `.pre.` replacement of `-`.
=> feat(ruby): add Gemfile.Lock updater

src/strategies/java-yoshi.ts, test/strategies/java-yoshi.ts
Fixes `Failed to find file: versions.txt` from the logs
This is a remnant from the refactor of the git file cache which throws a different error when a file is not found.
=> fix(java-yoshi): throw MissingRequiredFile error if no versions.txt found

__snapshots__/gemfile-lock.js, src/updaters/ruby/gemfile-lock.ts, test/updaters/gemfile-lock.ts
PR #1790 introduced support to update Gemfile.lock files. However this introduced an issue that updates random gem versions when the `package-name` (gemName) is not provided (which is optional). This fix ensures the gemName is valid before attempting to update the Gemfile.lock file.
Fixes  issue introduced in PR #1790
=> fix(ruby): gemfile.lock should not update when gem name is empty

__snapshots__/cli.js, src/bin/release-please.ts, src/index.ts
feat: export Strategy interface so external packages can implement
This should allow you to publish private configs in your own npm package and load via the CLI (you can already load configs programatically via `registerReleaseType` etc).
To make an external package dynamically loadable via the release-please CLI, export an `init()` method from your main file that registers your release-please extensions.
=> feat(cli): add ability to dynamically load release-please plugin

src/strategies/java-yoshi-mono-repo.ts, src/strategies/node.ts, src/util/filter-commits.ts, test/util/filter-commits.ts
Unknown changelog types were showing up in changelog.json leading to a lot of noise in the file.
=> fix: filter changelog.json commits based on changelog sections

__snapshots__/changelog-json.js, __snapshots__/java-yoshi-mono-repo.js, __snapshots__/node.js, src/updaters/changelog-json.ts
This will allow us to make a nicer downstream CHANGELOG, if no issue # is included in the commit title itself.
_Note: I've updated the corresponding spec._
=> feat(changelog.json): include referenced issues/prs

__snapshots__/generic-toml.js, docs/customizing.md, src/manifest.ts, src/strategies/base.ts, src/updaters/generic-toml.ts, src/util/toml-edit.ts, test/strategies/base.ts, test/updaters/fixtures/toml/invalid.txt, test/updaters/generic-toml.ts
=> feat: Add generic TOML updater

__snapshots__/generic-toml.js, package.json, test/updaters/fixtures/toml/v1.0.0.toml, test/updaters/generic-toml.ts
Fixes #1836 🦕
This PR updates  `@iarna/toml` the latest release of  `v3.0.0`, which supports up to TOML v1.0.0-rc.1.
While it does not explicitly state support for v1.0.0, it is worth noting that all structrural changes were introduced in the rc.1 (namely, heterogeneous arrays). 
For reference, you can see the test added in [cf0a809](https://github.com/googleapis/release-please/pull/1837/commits/cf0a809924973618ceec5364543b0f5ba72a2675)  failing (w/o updating the lib) here:
https://github.com/BradenM/release-please/actions/runs/4040572970/jobs/6946340169#step:8:5167
=> fix: Support TOML up to v1.0.0-rc.1 spec.

__snapshots__/changelog-json.js, src/updaters/changelog-json.ts, test/updaters/changelog-json.ts
In discussion with downstream implementers, we decideed that it would make it easier to customize the CHANGELOG generated if we pre-parsed the PR # suffix that GitHub adds to squashed commits.
=> feat(changelog.json): add pr suffix to issues array

__snapshots__/python.js, src/strategies/python.ts, test/fixtures/strategies/python/changelog.json, test/fixtures/strategies/python/setup.py, test/strategies/python.ts
Add support for generating `changelog.json` to python strategy.
Can be seen in action [here](https://github.com/bcoe/google-cloud-python/pull/4).
=> feat(changelog.json): implement changelog.json for python

src/github.ts
Found a small bug while going through debug logs: Github issues can be addressed with the /issues/ (plural) link, but the /issue one leads to a 404. The debug logs (visible in GH action logs) use the 404ing one.
Example:
- https://github.com/googleapis/release-please/issues/1848 works
- https://github.com/googleapis/release-please/issue/1848 is a 404
=> fix: github issues link

src/manifest.ts
Fixes #1864 🦕
Fixes https://github.com/google-github-actions/release-please-action/issues/546
Also fixes https://github.com/cloudquery/cloudquery/issues/7787
=> fix(sequential-calls): Use push instead of concat when returning releases

docs/manifest-releaser.md
=> fix(docs): :memo: Adding missing docs for include-component-in-tag

README.md, __snapshots__/cli.js, __snapshots__/sfdx-project-json.js, docs/customizing.md, src/factory.ts, src/strategies/sfdx.ts, src/updaters/sfdx/sfdx-project-json.ts, test/fixtures/strategies/sfdx/sfdx-project.json, test/strategies/sfdx.ts, test/updaters/fixtures/sfdx-project.json, test/updaters/sfdx-project-json.ts
=> refactor: rename Salesforce to sfdx

docs/customizing.md
Presently, finding the correct syntax is not easy, as it is not provided in any of the following:
* https://github.com/googleapis/release-please/blob/122820d/docs/customizing.md
* https://github.com/googleapis/release-please/blob/122820d/docs/manifest-releaser.md
* https://github.com/googleapis/release-please/blob/122820d/README.md
It can be found in the following places:
* https://github.com/googleapis/release-please/blob/122820d/schemas/config.json#L110-L118
* https://github.com/googleapis/release-please/blob/122820d/test/fixtures/manifest/config/extra-files.json
Related:
* https://github.com/google-github-actions/release-please-action/blob/ee9822e/README.md#adding-additional-files
---
Edit: to make it easier to skim over this, could be shortened to just:
```json
{
"extra-files": …
```
=> docs: show `extra-files` syntax for generic files

__snapshots__/setup-cfg.js, src/updaters/python/setup-cfg.ts, test/updaters/fixtures/setup-big-version.cfg, test/updaters/setup-cfg.ts
=> fix(python): handle large version numbers in setup.cfg

docs/manifest-releaser.md, schemas/config.json, src/manifest.ts, src/util/commit-exclude.ts, src/util/commit-split.ts, src/util/commit-utils.ts, test/fixtures/manifest/config/exclude-paths.json, test/manifest.ts, test/util/commit-exclude.ts
Idea is to exclude commits if all files in those commits are from specific paths.
In my case I have multiple packages in `packages` and `.` umbrella package. Some of packages are different and handled by different workflow and I need to exclude those from umbrella.
Tested only with `config-file`
Note: I think it is possible to break it with `"package/foo":{"exclude-paths":["package/foo"]}` but I did not test it yet.
Fixes #908🦕
=> feat: allow excluding file paths to filter out commits

README.md
=> docs: clarify that the commit override does not work on plain merges

src/manifest.ts
Current implementation when setting up boolean `needsBootstrap` considers only github releases.
In setup of one umbrella release and multiple packages without github release (only tags) that leads to commit search up to maximum depth.
Fixes #1903 🦕
=> fix: needsBootstrap computation considers also tags

docs/manifest-releaser.md
Github tightened the permissions sometime last year, so you now need to tell it to give the action permissions to modify and create PRs.
Fixes #1925
=> docs: Add permissions stanza to manifest-releaser github script

README.md
=> docs: remove invalid expo example link

__snapshots__/cli.js, docs/cli.md, docs/customizing.md, docs/manifest-releaser.md, schemas/config.json, src/bin/release-please.ts, src/factories/versioning-strategy-factory.ts, src/factory.ts, src/manifest.ts, src/version.ts, src/versioning-strategies/default.ts, src/versioning-strategies/dependency-manifest.ts, src/versioning-strategies/prerelease.ts, test/cli.ts, test/factory.ts, test/manifest.ts, test/version.ts, test/versioning-strategies/prerelease.ts
Fixes #2082 🦕 by introducing an argument to the `prerelease` versioning strategy.
It also deals with bumping versions with prerelease, but not having a number in the prerelease part in the following ways  
- `2.0.0-beta` will get bumped to `2.0.0-beta.1` if there are breaking changes or less
- `1.2.0-beta` will get bumped to `1.2.0-beta.1` if there are featurer or less
- `1.2.2-beta` will get bumped to `1.2.2-beta.1` if there are only patches.
The current behaviour of prelrease, ie. bumping `1.1.1-beta01` to `1.1.1-beta02` is preserved.
=> feat: prerelease type

__snapshots__/package-lock-json.js, src/updaters/node/package-lock-json.ts, test/updaters/fixtures/package-lock-v3-workspace.json, test/updaters/package-lock-json.ts
=> feat: update package-lock.json workspace entiry versions

src/strategies/base.ts, test/fixtures/release-notes/multiple-with-root.txt, test/manifest.ts
=> fix: releasable units should use version from pull-request body (fixes #2101)

.github/workflows/ci.yaml
This should help us prevent #2116 in the future. After we fix the build issue, then we can optionally make it a required check.
=> ci: add workflow job for building the action against head

__snapshots__/cli.js, docs/cli.md, docs/customizing.md, schemas/config.json, src/bin/release-please.ts, src/manifest.ts, src/plugins/merge.ts, src/strategies/base.ts, src/strategies/dotnet-yoshi.ts, src/updaters/release-please-config.ts, test/manifest.ts
The function already exists, but it cannot be changed as a parameter for package users. This update makes the setting available to everyone.
**The `pull-request-footer` option has been added to the configuration file.** When tracked, it completely matches the settings of the `pull-request-header`. The PR generator was already equipped with a `footer` parameter by default, so you just need to pass this setting along.
Fixes #2114 🦕
=> feat: customize PR body footer

src/manifest.ts
---
I did not open an issue for this first. But the old behavior of using `Promise.all` to set labels was causing GitHub API errors for us on https://github.com/npm/cli in CI. I've lost the logs for CI runs when this was happening but I've been using this fix in our fork (which we wan't to get off of, hence the PR) as it fixed the issue.
=> fix: set PR labels serially

src/util/pull-request-body.ts, test/fixtures/release-notes/single-prerelease.txt, test/util/pull-request-body.ts
---
This fixes pull request body parsing for single prereleases. Previously the regex used to match the title would include the rest of the title link as well. This PR changes the regex to match everything up until the next `]`.
Here's the output of the new test without this change:
```diff
AssertionError: expected '3.2.7-pre.0](https://www.github.com/g…' to deeply equal '3.2.7-pre.0'
+ expected - actual
-3.2.7-pre.0](https://www.github.com/googleapis/java-asset/compare/v3.2.6...v3.2.7-pre.0) (2021-10-20)
+3.2.7-pre.0
```
=> fix: correctly parse standalone prerelease PR body

__snapshots__/node-workspace.js, __snapshots__/package-json.js, package-lock.json, package.json, src/plugins/node-workspace.ts, src/plugins/workspace.ts, src/updaters/node/package-json.ts, test/helpers.ts, test/plugins/node-workspace.ts, test/updaters/fixtures/package-with-dependencies.json, test/updaters/package-json.ts
Refactors the node-workspace plugin to  use the internal workspace-plugin graph/dependency logic and built-in
package.json updaters to update the content. We do not need to rely on lerna internals.
Fixes #2116 
feat: PackageJson updater can update dependencies
=> feat(deps): refactor node-workspace plugin to drop lerna-lite/core

__snapshots__/github.js, src/github.ts, test/fixtures/commits-since-rebase.json, test/github.ts
Fixes #2140 🦕
This has the effect of not associating a PR with any of the commits from a PR that is rebased and merged. Previously it would associate the PR only with the first commit, but this would also add all the files from the PR to that first commit.
A different (or future) solution would be to decouple connecting PRs and files with commits. I considered that but thought that solution would increase the scope too much. I'm open to reworking the PR in that direction though.
=> fix: backfill files by commit for rebased PRs

src/strategies/php.ts, test/strategies/php.ts
This updates the `php` default strategy to update a `VERSION` file in the root of the repo if it exists. This will be useful for some PHP libraries to track which versions are being used.
=> feat: update VERSION file in PHP repo if it exists

src/index.ts, src/manifest.ts
This allows the release-please action and other to reference the return types of `createReleases()` and `createPullRequests()`
=> feat(types): export types exposed by Manifest for use downstream

__snapshots__/manifest.js, src/manifest.ts, src/plugins/merge.ts, test/manifest.ts
Fixes #2142  🦕
This works by looping through `repositoryConfig` and getting the first set value for both `pullRequestHeader` and `pullRequestFooter`. This means they could possibly come from different components in a manifest release.
I thought about only using config values from `repositoryConfig[ROOT_PROJECT_PATH]`. I didn't have strong feelings either way so I went with the solution I felt would be less surprising. But I'd be open to reworking the PR to this alternate solution.
=> fix: pass pull request header and footer options to merge plugin

owlbot.py
Owlbot post-processing is touching the `release-please-config.json` and I don't see an easy way to disable it. This repo does not need owlbot post-processing
=> build: disable owlbot from touching files in this repo

src/strategies/php-yoshi.ts, test/strategies/php-yoshi.ts
addresses https://github.com/googleapis/release-please/issues/2198
This is the simplest solution, which will not effect `php.ts`. However, `RootComposerUpdatePackages` contains problems with it's implementation that will be addressed in another PR.
=> fix(php): do not add version to root version map

__snapshots__/php-composer-update-packages.js, __snapshots__/root-composer-update-packages.js, src/strategies/php-yoshi.ts, src/strategies/php.ts, src/updaters/php/root-composer-update-packages.ts, test/updaters/php-composer-update-packages.ts, test/updaters/root-composer-update-packages.ts
addresses https://github.com/googleapis/release-please/issues/2198
Marked as a `feat` since it changes the behavior of `RootComposerUpdatePackage` by always updating `version` in `composer.json`. 
**IMPORTANT**: The behavior of the php strategy (`src/strategies/php.ts`) will **not** change, as `version` was already being set in the `versionsMap`. The only difference in the php strategy is in the case where `composer.json` includes a `replace` section: the "version" key will no longer be added to it. This is the desired behavior, as adding such a string to `replace` results in a composer exception.
=> feat: set 'version' of composer.json in RootComposerUpdatePackages

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/ISSUE_TEMPLATE/support_request.md, README.md, owlbot.py
Release Please is an OSS project released as a community contribution. It is not part of the Google Cloud SDK.
---
Release please was using the default templates for support requests. This created confusion for customers.
=> docs: remove reference to support contracts

src/strategies/php-yoshi.ts, test/strategies/php-yoshi.ts
Php-yoshi releases only track the `VERSION` file in subdirectories and skips tracking it for the root. This is the same as PR #2153 but for `yoshi-php` releases instead of `php`.
=> feat: update VERSION file in php-yoshi repo if it exists

docs/customizing.md, src/manifest.ts, src/strategies/base.ts, test/strategies/base.ts
=> fix: Support generic updater

__snapshots__/package-json.js, src/plugins/node-workspace.ts, src/updaters/node/package-json.ts, test/updaters/package-json.ts
The "updatePeerDependencies" option currently operates as a "considerPeerDependencies" option. What this means is that if a package only has a peer dependency on another, then that will not be considered and no update will be made (as if there was no dependency). If a package has a peer dependency as well as another dependency, for instance a dev dependency, then the peer dependency is updated regardless.
This propagates the "updatePeerDependencies" option to the PackageJson updater so that it can omit updates to the peer dependencies.
It isn't completely clear what the intended behavior here is. This update behavior matches my current use-case, but it is possible it could be a problem for others. In which case there could be two different options (but the current name does seem like it …
=> fix: Disable updating peer dependencies when updatePeerDependencies is false.

docs/cli.md, schemas/config.json
Just fixing a typo of `prerelese` to `prerelease`. Let me know if I should still make an issue first. Thanks for working on this project!
=> docs: tweak typo in the spelling of prerelease

.github/workflows/ci.yaml, README.md, docs/manifest-releaser.md
See https://github.com/googleapis/release-please-action/issues/980.
Fixes #2288 🦕
=> fix(ci): use correct release-please-action domain after organization url was changed

src/strategies/php-yoshi.ts, test/strategies/php-yoshi.ts
Allow for adding `BEGIN_VERSION_OVERRIDE` to PHP release in order to override the release version from the PR for specific components. 
Example PR body:
```
// normal PR body (from owlbot or otherwise)
// at the end of the PR
BEGIN_VERSION_OVERRIDE
PubSub: 2.0.0-RC1
Core: 1.45.0
END_VERSION_OVERRIDE
```
=> feat: support BEGIN_VERSION_OVERRIDE in php-yoshi

__snapshots__/default-changelog-notes.js, src/changelog-notes/default.ts, test/changelog-notes/default-changelog-notes.ts
This makes sure to only escape HTML tags that are not within inline code blocks as these are handled explicitly and not rendered the same way they are outside of code blocks.
Fixes #2366  🦕
Example, a commit such as the following:
```
feat: render all imagesets as <picture> `<picture>` `` `<picture>` ``
```
would render as the following markdown:
render all imagesets as &lt;picture&gt; `<picture>` `` `<picture>` ``
=> fix: don't escape html tags inside of inline code in release notes

src/commit.ts, test/commits.ts, test/fixtures/commit-messages/multiple-commits-single-message.txt
This PR enhances the breaking change detection mechanism and improves the parsing of commit messages to handle multiple conventional commits and nested commit blocks mentioned in #2357 
- Added additional breaking change detection from the commit body in `toConventionalChangelogFormat` and `postProcessCommits` functions.
- Enhanced `splitMessages` function to:
- Separate conventional commits within the main message.
- Extract nested commits enclosed in `BEGIN_NESTED_COMMIT`/`END_NESTED_COMMIT` blocks.
- Preserve the original message structure outside of nested commit blocks.
- Handle multiple nested commits and conventional commits in a single message.
- Updated tests in `test/commits.ts` to reflect the changes and added new test cases for multiple commits in a single message.
- Added a …
=> feat: handle multiple commits in a single message

package-lock.json, package.json, src/updaters/generic-json.ts, src/updaters/generic-toml.ts, src/updaters/generic-yaml.ts, test/updaters/generic-json.ts, test/updaters/generic-toml.ts, test/updaters/generic-yaml.ts
`jsonpath` packages is unmaintained. `jsonpath-plus` is not in active development, but is more maintained.
There is a minor behavioral change in that invalid `jsonpath` entries provided no longer throw an exception and crash the execution. Instead, it's treated as if there are no matching `jsonpath` entries (no-op).
=> fix(deps): replace jsonpath with jsonpath-plus

README.md, __snapshots__/cli.js, __snapshots__/r-description.js, src/factory.ts, src/strategies/r.ts, src/updaters/r/description.ts, src/updaters/r/news.ts, test/strategies/r.ts, test/updaters/fixtures/r/DESCRIPTION, test/updaters/r-description.ts
Fixes #2151 🦕
I'm new to typescript and javascript, so please take this as a work in progress.
One thing that I couldn't figure out how to handle was how to create a NEWS.md file by default, without explicitly having to specify `--changelog-path=NEWS.md`. It would be nice if this could be a per-strategy default, but maybe I'm missing something obvious and otherwise I guess that should go into its own issue.
Another issue is that typically R packages have a NEWS.md file with a somewhat different structure, and it doesn't expect a top-level header but instead a package version (typically including name, but I don't think that's necessary). Otherwise some of the tools used in the R community, such as pkgdown have a hard time dealing with the changelogs. A typical NEWS.md file could look like …
=> feat: add strategy for R packages

README.md
Modern Python projects favor configuring with `pyproject.toml` over the `setup.py`.
https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
> Starting with [PEP 621](https://peps.python.org/pep-0621), the Python community selected `pyproject.toml` as a standard way of specifying project metadata. `Setuptools` has adopted this standard and will use the information contained in this file as an input in the build process.
=> docs(python): suggest pyproject.toml instead of setup.py

src/manifest.ts, test/cli.ts, test/manifest.ts
This pull request gives the caller of the Manifest.createRelease with the pull request number. This is for the Release Please bot's new capability to tag a commit with the Release Please pull request numbers. https://github.com/googleapis/repo-automation-bots/blob/main/packages/release-please/src/release-please.ts#L386 will receive the pull request number. The CreatedRelease interface extends GitHubRelease, which has commit SHA for the release.
b/b/394646919
=> feat: Manifest.createRelease to return PR numbers

src/strategies/go.ts, test/fixtures/strategies/go/internal/version/version.go, test/strategies/go.ts
Make the `Go` strategy use the `versionFile` value if it's defined.
Fixes #2541
=> fix: use version-file if it's set for go projects
